In [4]:
import pandas as pd

In [5]:
feb_df = pd.read_csv("/Users/amber/Desktop/GitHub/Tableau-DataClean/csvs/JC-202102-citibike-tripdata.csv")
feb_df

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,121DD7DD23CB1335,docked_bike,2021-02-03 23:11:28,2021-02-03 23:18:28,Hoboken Ave at Monmouth St,JC105,Christ Hospital,JC034,40.735208,-74.046964,40.734786,-74.050444,member
1,FD73FB85F008349D,docked_bike,2021-02-27 16:34:05,2021-02-27 16:56:40,Newport Pkwy,JC008,Marin Light Rail,JC013,40.728744,-74.032108,40.714584,-74.042817,member
2,39F9E6663CB5FDF6,docked_bike,2021-02-26 23:16:04,2021-02-26 23:22:25,Journal Square,JC103,Baldwin at Montgomery,JC020,40.733670,-74.062500,40.723659,-74.064194,member
3,A64745CB0792EC6F,docked_bike,2021-02-24 16:51:50,2021-02-24 17:16:09,Hoboken Ave at Monmouth St,JC105,Hoboken Ave at Monmouth St,JC105,40.735208,-74.046963,40.735208,-74.046964,casual
4,75CC76EB9543764A,docked_bike,2021-02-24 20:44:16,2021-02-24 20:44:46,Hoboken Ave at Monmouth St,JC105,Hoboken Ave at Monmouth St,JC105,40.735208,-74.046963,40.735208,-74.046964,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4876,3F8FD9A051C0E3DA,docked_bike,2021-02-24 18:05:45,2021-02-24 18:12:27,Columbus Drive,JC014,Newport Pkwy,JC008,40.718355,-74.038914,40.728745,-74.032108,member
4877,B91F3593C0C06D04,docked_bike,2021-02-22 18:22:04,2021-02-22 18:28:45,Columbus Drive,JC014,Newport Pkwy,JC008,40.718355,-74.038914,40.728745,-74.032108,member
4878,A790954A017D07CB,docked_bike,2021-02-13 12:21:49,2021-02-13 12:27:51,Columbus Drive,JC014,Newport Pkwy,JC008,40.718355,-74.038914,40.728745,-74.032108,member
4879,42B1932D06CEE034,docked_bike,2021-02-25 11:20:29,2021-02-25 11:25:23,Columbus Drive,JC014,Morris Canal,JC072,40.718355,-74.038914,40.712419,-74.038526,member
4880,F71732ECE7CD02CF,docked_bike,2021-02-19 13:59:22,2021-02-19 14:05:47,Columbus Drive,JC014,Newport Pkwy,JC008,40.718355,-74.038914,40.728745,-74.032108,member

In [16]:
feb_df_station = feb_df.loc[:, 'start_station_name':'start_station_id']
feb_df_station = feb_df_station.drop_duplicates()
feb_df_station.sort_values(by='start_station_id')
feb_df_station.reset_index(drop=True, inplace=True)
feb_df_station.to_csv(r'/Users/amber/Desktop/GitHub/Tableau-DataClean/csvs/start_station_ids.csv', index=False)

In [17]:
feb_df_station_end = feb_df.loc[:, 'end_station_name':'end_station_id']
feb_df_station_end = feb_df_station_end.drop_duplicates()
feb_df_station_end.reset_index(drop=True, inplace=True)
feb_df_station_end.to_csv(r'/Users/amber/Desktop/GitHub/Tableau-DataClean/csvs/end_station_ids.csv', index=False)

In [14]:
feb_df_station.to_dict('list')

{'start_station_name': ['Hoboken Ave at Monmouth St',
  'Newport Pkwy',
  'Journal Square',
  'Newark Ave',
  '5 Corners Library',
  'Washington St',
  'Montgomery St',
  'York St',
  'Marin Light Rail',
  'Morris Canal',
  'Communipaw & Berry Lane',
  'Monmouth and 6th',
  'Baldwin at Montgomery',
  'Liberty Light Rail',
  'Pershing Field',
  'Heights Elevator',
  'Astor Place',
  'Sip Ave',
  'McGinley Square',
  'Jackson Square',
  'Harborside',
  'Paulus Hook',
  'Warren St',
  'Union St',
  'Glenwood Ave',
  'Bergen Ave',
  'Oakland Ave',
  'Hilltop',
  'Jersey & 3rd',
  'JC Medical Center',
  'Newport PATH',
  'Lafayette Park',
  'Brunswick St',
  'Brunswick & 6th',
  'Hamilton Park',
  'Dey St',
  'Riverview Park',
  'Fairmount Ave',
  'Grove St PATH',
  'Grand St',
  'Christ Hospital',
  'Columbus Dr at Exchange Pl',
  'Van Vorst Park',
  'Leonard Gordon Park',
  'Essex Light Rail',
  'Lincoln Park',
  'Manila & 1st',
  'Dixon Mills',
  'City Hall',
  'Jersey & 6th St',
  'Columbus Drive'],
 'start_station_id': ['JC105',
  'JC008',
  'JC103',
  'JC032',
  'JC018',
  'JC098',
  'JC099',
  'JC096',
  'JC013',
  'JC072',
  'JC084',
  'JC075',
  'JC020',
  'JC052',
  'JC024',
  'JC059',
  'JC077',
  'JC056',
  'JC055',
  'JC063',
  'JC104',
  'JC002',
  'JC006',
  'JC051',
  'JC094',
  'JC095',
  'JC022',
  'JC019',
  'JC074',
  'JC011',
  'JC066',
  'JC078',
  'JC023',
  'JC081',
  'JC009',
  'JC065',
  'JC057',
  'JC093',
  'JC005',
  'JC102',
  'JC034',
  'JC106',
  'JC035',
  'JC080',
  'JC038',
  'JC053',
  'JC082',
  'JC076',
  'JC003',
  'JC027',
  'JC014']}

In [2]:
import pandas as pd

jan_df = pd.read_csv("/Users/amber/Desktop/GitHub/Tableau-DataClean/csvs/JC-202101-citibike-tripdata.csv")
jan_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,266,2021-01-01 00:03:35.5100,2021-01-01 00:08:01.7770,3273,Manila & 1st,40.721651,-74.042884,3209,Brunswick St,40.724176,-74.050656,42494,Subscriber,1988,1
1,1543,2021-01-01 00:23:32.9250,2021-01-01 00:49:16.0830,3681,Grand St,40.715178,-74.037683,3213,Van Vorst Park,40.718489,-74.047727,45343,Customer,1996,2
2,1461,2021-01-01 00:23:50.7940,2021-01-01 00:48:12.5660,3681,Grand St,40.715178,-74.037683,3213,Van Vorst Park,40.718489,-74.047727,31794,Customer,1995,1
3,793,2021-01-01 00:31:09.0770,2021-01-01 00:44:22.9430,3185,City Hall,40.717732,-74.043845,3199,Newport Pkwy,40.728745,-74.032108,42316,Customer,1969,0
4,596,2021-01-01 00:35:52.1900,2021-01-01 00:45:48.7740,3639,Harborside,40.719252,-74.034234,3209,Brunswick St,40.724176,-74.050656,32575,Customer,1969,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11619,2476,2021-01-31 20:16:05.4700,2021-01-31 20:57:22.0110,3187,Warren St,40.721124,-74.038051,3483,Montgomery St,40.719420,-74.050990,44852,Subscriber,1958,1
11620,147,2021-01-31 21:05:05.2090,2021-01-31 21:07:32.8660,3186,Grove St PATH,40.719586,-74.043117,3187,Warren St,40.721124,-74.038051,46538,Subscriber,1972,1
11621,660,2021-01-31 21:06:23.5880,2021-01-31 21:17:23.8420,3211,Newark Ave,40.721525,-74.046305,3276,Marin Light Rail,40.714584,-74.042817,44398,Subscriber,1987,2
11622,384,2021-01-31 21:16:37.8220,2021-01-31 21:23:02.1240,3205,JC Medical Center,40.716540,-74.049638,3268,Lafayette Park,40.713464,-74.062859,41400,Subscriber,1989,1
11623,356,2021-01-31 23:24:50.8810,2021-01-31 23:30:47.3030,3639,Harborside,40.719252,-74.034234,3186,Grove St PATH,40.719586,-74.043117,43766,Subscriber,1994,1

In [13]:
jan_df.columns = jan_df.columns.str.replace(' ', '_')
jan_df

,tripduration,starttime,stoptime,start_station_id,start_station_name,start_station_latitude,start_station_longitude,end_station_id,end_station_name,end_station_latitude,end_station_longitude,bikeid,usertype,birth_year,gender
0,266,2021-01-01 00:03:35.5100,2021-01-01 00:08:01.7770,3273,Manila & 1st,40.721651,-74.042884,3209,Brunswick St,40.724176,-74.050656,42494,Subscriber,1988,1
1,1543,2021-01-01 00:23:32.9250,2021-01-01 00:49:16.0830,3681,Grand St,40.715178,-74.037683,3213,Van Vorst Park,40.718489,-74.047727,45343,Customer,1996,2
2,1461,2021-01-01 00:23:50.7940,2021-01-01 00:48:12.5660,3681,Grand St,40.715178,-74.037683,3213,Van Vorst Park,40.718489,-74.047727,31794,Customer,1995,1
3,793,2021-01-01 00:31:09.0770,2021-01-01 00:44:22.9430,3185,City Hall,40.717732,-74.043845,3199,Newport Pkwy,40.728745,-74.032108,42316,Customer,1969,0
4,596,2021-01-01 00:35:52.1900,2021-01-01 00:45:48.7740,3639,Harborside,40.719252,-74.034234,3209,Brunswick St,40.724176,-74.050656,32575,Customer,1969,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11619,2476,2021-01-31 20:16:05.4700,2021-01-31 20:57:22.0110,3187,Warren St,40.721124,-74.038051,3483,Montgomery St,40.719420,-74.050990,44852,Subscriber,1958,1
11620,147,2021-01-31 21:05:05.2090,2021-01-31 21:07:32.8660,3186,Grove St PATH,40.719586,-74.043117,3187,Warren St,40.721124,-74.038051,46538,Subscriber,1972,1
11621,660,2021-01-31 21:06:23.5880,2021-01-31 21:17:23.8420,3211,Newark Ave,40.721525,-74.046305,3276,Marin Light Rail,40.714584,-74.042817,44398,Subscriber,1987,2
11622,384,2021-01-31 21:16:37.8220,2021-01-31 21:23:02.1240,3205,JC Medical Center,40.716540,-74.049638,3268,Lafayette Park,40.713464,-74.062859,41400,Subscriber,1989,1
11623,356,2021-01-31 23:24:50.8810,2021-01-31 23:30:47.3030,3639,Harborside,40.719252,-74.034234,3186,Grove St PATH,40.719586,-74.043117,43766,Subscriber,1994,1

In [31]:
new_jan_df = pd.merge(jan_df, feb_df_station, on='start_station_name')
new_jan_df

,tripduration,starttime,stoptime,start_station_id_x,start_station_name,start_station_latitude,start_station_longitude,end_station_id,end_station_name,end_station_latitude,end_station_longitude,bikeid,usertype,birth_year,gender,start_station_id_y
0,266,2021-01-01 00:03:35.5100,2021-01-01 00:08:01.7770,3273,Manila & 1st,40.721651,-74.042884,3209,Brunswick St,40.724176,-74.050656,42494,Subscriber,1988,1,JC082
1,1710,2021-01-01 14:47:19.7140,2021-01-01 15:15:50.6870,3273,Manila & 1st,40.721651,-74.042884,3185,City Hall,40.717732,-74.043845,42422,Subscriber,1969,1,JC082
2,374,2021-01-02 09:18:47.6460,2021-01-02 09:25:02.0330,3273,Manila & 1st,40.721651,-74.042884,3270,Jersey & 6th St,40.725289,-74.045572,40464,Subscriber,1987,1,JC082
3,239,2021-01-02 10:05:45.8090,2021-01-02 10:09:45.3650,3273,Manila & 1st,40.721651,-74.042884,3203,Hamilton Park,40.727596,-74.044247,42368,Subscriber,1981,1,JC082
4,250,2021-01-02 11:45:06.8420,2021-01-02 11:49:17.1970,3273,Manila & 1st,40.721651,-74.042884,3638,Washington St,40.724294,-74.035483,45364,Subscriber,1988,2,JC082
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11619,2322,2021-01-28 12:47:43.6810,2021-01-28 13:26:26.0380,3196,Riverview Park,40.744319,-74.043991,3195,Sip Ave,40.730897,-74.063913,43361,Subscriber,1998,2,JC057
11620,1285,2021-01-28 14:44:09.1600,2021-01-28 15:05:34.3550,3196,Riverview Park,40.744319,-74.043991,3273,Manila & 1st,40.721651,-74.042884,44376,Subscriber,1968,1,JC057
11621,549,2021-01-29 19:42:20.8910,2021-01-29 19:51:29.9640,3196,Riverview Park,40.744319,-74.043991,3196,Riverview Park,40.744319,-74.043991,40954,Subscriber,1998,2,JC057
11622,562,2021-01-30 12:00:28.5500,2021-01-30 12:09:51.3200,3196,Riverview Park,40.744319,-74.043991,3269,Brunswick & 6th,40.726012,-74.050389,40954,Customer,1996,1,JC057
11623,990,2021-01-30 16:08:19.5370,2021-01-30 16:24:50.3170,3196,Riverview Park,40.744319,-74.043991,3187,Warren St,40.721124,-74.038051,39329,Subscriber,1988,1,JC057

In [32]:
new_jan_df = pd.merge(new_jan_df, feb_df_station_end, on='end_station_name')
new_jan_df

,tripduration,starttime,stoptime,start_station_id_x,start_station_name,start_station_latitude,start_station_longitude,end_station_id_x,end_station_name,end_station_latitude,end_station_longitude,bikeid,usertype,birth_year,gender,start_station_id_y,end_station_id_y
0,266,2021-01-01 00:03:35.5100,2021-01-01 00:08:01.7770,3273,Manila & 1st,40.721651,-74.042884,3209,Brunswick St,40.724176,-74.050656,42494,Subscriber,1988,1,JC082,JC023
1,296,2021-01-02 23:16:11.3820,2021-01-02 23:21:08.3150,3273,Manila & 1st,40.721651,-74.042884,3209,Brunswick St,40.724176,-74.050656,42419,Subscriber,1988,1,JC082,JC023
2,269,2021-01-04 13:16:00.9080,2021-01-04 13:20:30.7690,3273,Manila & 1st,40.721651,-74.042884,3209,Brunswick St,40.724176,-74.050656,38460,Subscriber,1982,1,JC082,JC023
3,207,2021-01-05 22:53:03.5880,2021-01-05 22:56:30.7910,3273,Manila & 1st,40.721651,-74.042884,3209,Brunswick St,40.724176,-74.050656,47258,Subscriber,1988,1,JC082,JC023
4,238,2021-01-08 23:10:38.3990,2021-01-08 23:14:36.4990,3273,Manila & 1st,40.721651,-74.042884,3209,Brunswick St,40.724176,-74.050656,47257,Subscriber,1988,1,JC082,JC023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11612,104,2021-01-12 07:24:12.2750,2021-01-12 07:25:56.3690,3201,Dey St,40.737711,-74.066921,3201,Dey St,40.737711,-74.066921,28364,Subscriber,1966,1,JC065,JC065
11613,195,2021-01-10 15:25:53.3320,2021-01-10 15:29:09.3190,3220,5 Corners Library,40.734961,-74.059503,3201,Dey St,40.737711,-74.066921,28364,Subscriber,1961,1,JC018,JC065
11614,369,2021-01-12 22:09:16.7860,2021-01-12 22:15:25.9820,3220,5 Corners Library,40.734961,-74.059503,3201,Dey St,40.737711,-74.066921,46395,Subscriber,1998,1,JC018,JC065
11615,341,2021-01-12 22:09:52.5970,2021-01-12 22:15:34.1270,3220,5 Corners Library,40.734961,-74.059503,3201,Dey St,40.737711,-74.066921,41547,Customer,1969,0,JC018,JC065
11616,820,2021-01-19 14:11:14.0330,2021-01-19 14:24:54.8420,3196,Riverview Park,40.744319,-74.043991,3201,Dey St,40.737711,-74.066921,44698,Customer,1969,0,JC057,JC065

In [33]:
new_jan_df.drop(columns=['start_station_id_x', 'end_station_id_x'], inplace=True)
new_jan_df

,tripduration,starttime,stoptime,start_station_name,start_station_latitude,start_station_longitude,end_station_name,end_station_latitude,end_station_longitude,bikeid,usertype,birth_year,gender,start_station_id_y,end_station_id_y
0,266,2021-01-01 00:03:35.5100,2021-01-01 00:08:01.7770,Manila & 1st,40.721651,-74.042884,Brunswick St,40.724176,-74.050656,42494,Subscriber,1988,1,JC082,JC023
1,296,2021-01-02 23:16:11.3820,2021-01-02 23:21:08.3150,Manila & 1st,40.721651,-74.042884,Brunswick St,40.724176,-74.050656,42419,Subscriber,1988,1,JC082,JC023
2,269,2021-01-04 13:16:00.9080,2021-01-04 13:20:30.7690,Manila & 1st,40.721651,-74.042884,Brunswick St,40.724176,-74.050656,38460,Subscriber,1982,1,JC082,JC023
3,207,2021-01-05 22:53:03.5880,2021-01-05 22:56:30.7910,Manila & 1st,40.721651,-74.042884,Brunswick St,40.724176,-74.050656,47258,Subscriber,1988,1,JC082,JC023
4,238,2021-01-08 23:10:38.3990,2021-01-08 23:14:36.4990,Manila & 1st,40.721651,-74.042884,Brunswick St,40.724176,-74.050656,47257,Subscriber,1988,1,JC082,JC023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11612,104,2021-01-12 07:24:12.2750,2021-01-12 07:25:56.3690,Dey St,40.737711,-74.066921,Dey St,40.737711,-74.066921,28364,Subscriber,1966,1,JC065,JC065
11613,195,2021-01-10 15:25:53.3320,2021-01-10 15:29:09.3190,5 Corners Library,40.734961,-74.059503,Dey St,40.737711,-74.066921,28364,Subscriber,1961,1,JC018,JC065
11614,369,2021-01-12 22:09:16.7860,2021-01-12 22:15:25.9820,5 Corners Library,40.734961,-74.059503,Dey St,40.737711,-74.066921,46395,Subscriber,1998,1,JC018,JC065
11615,341,2021-01-12 22:09:52.5970,2021-01-12 22:15:34.1270,5 Corners Library,40.734961,-74.059503,Dey St,40.737711,-74.066921,41547,Customer,1969,0,JC018,JC065
11616,820,2021-01-19 14:11:14.0330,2021-01-19 14:24:54.8420,Riverview Park,40.744319,-74.043991,Dey St,40.737711,-74.066921,44698,Customer,1969,0,JC057,JC065

In [34]:
new_jan_df.rename(columns = {'start_station_id_y':'start_station_id', 'end_station_id_y':'end_station_id'}, inplace=True)
new_jan_df

,tripduration,starttime,stoptime,start_station_name,start_station_latitude,start_station_longitude,end_station_name,end_station_latitude,end_station_longitude,bikeid,usertype,birth_year,gender,start_station_id,end_station_id
0,266,2021-01-01 00:03:35.5100,2021-01-01 00:08:01.7770,Manila & 1st,40.721651,-74.042884,Brunswick St,40.724176,-74.050656,42494,Subscriber,1988,1,JC082,JC023
1,296,2021-01-02 23:16:11.3820,2021-01-02 23:21:08.3150,Manila & 1st,40.721651,-74.042884,Brunswick St,40.724176,-74.050656,42419,Subscriber,1988,1,JC082,JC023
2,269,2021-01-04 13:16:00.9080,2021-01-04 13:20:30.7690,Manila & 1st,40.721651,-74.042884,Brunswick St,40.724176,-74.050656,38460,Subscriber,1982,1,JC082,JC023
3,207,2021-01-05 22:53:03.5880,2021-01-05 22:56:30.7910,Manila & 1st,40.721651,-74.042884,Brunswick St,40.724176,-74.050656,47258,Subscriber,1988,1,JC082,JC023
4,238,2021-01-08 23:10:38.3990,2021-01-08 23:14:36.4990,Manila & 1st,40.721651,-74.042884,Brunswick St,40.724176,-74.050656,47257,Subscriber,1988,1,JC082,JC023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11612,104,2021-01-12 07:24:12.2750,2021-01-12 07:25:56.3690,Dey St,40.737711,-74.066921,Dey St,40.737711,-74.066921,28364,Subscriber,1966,1,JC065,JC065
11613,195,2021-01-10 15:25:53.3320,2021-01-10 15:29:09.3190,5 Corners Library,40.734961,-74.059503,Dey St,40.737711,-74.066921,28364,Subscriber,1961,1,JC018,JC065
11614,369,2021-01-12 22:09:16.7860,2021-01-12 22:15:25.9820,5 Corners Library,40.734961,-74.059503,Dey St,40.737711,-74.066921,46395,Subscriber,1998,1,JC018,JC065
11615,341,2021-01-12 22:09:52.5970,2021-01-12 22:15:34.1270,5 Corners Library,40.734961,-74.059503,Dey St,40.737711,-74.066921,41547,Customer,1969,0,JC018,JC065
11616,820,2021-01-19 14:11:14.0330,2021-01-19 14:24:54.8420,Riverview Park,40.744319,-74.043991,Dey St,40.737711,-74.066921,44698,Customer,1969,0,JC057,JC065

In [36]:
new_jan_df = new_jan_df.reindex(columns=['tripduration', 'starttime', 'stoptime', 'start_station_id', 'start_station_name', 'start_station_latitude', 'start_station_longitude', 'end_station_id', 'end_station_name', 'end_station_latitude', 'end_station_longitude', 'bikeid', 'usertype', 'birth_year', 'gender'])
new_jan_df.to_csv(r'/Users/amber/Desktop/GitHub/Tableau-DataClean/csvs/JC-202101-citibike-tripdata-CLEANED.csv', index=False)
new_jan_df

,tripduration,starttime,stoptime,start_station_id,start_station_name,start_station_latitude,start_station_longitude,end_station_id,end_station_name,end_station_latitude,end_station_longitude,bikeid,usertype,birth_year,gender
0,266,2021-01-01 00:03:35.5100,2021-01-01 00:08:01.7770,JC082,Manila & 1st,40.721651,-74.042884,JC023,Brunswick St,40.724176,-74.050656,42494,Subscriber,1988,1
1,296,2021-01-02 23:16:11.3820,2021-01-02 23:21:08.3150,JC082,Manila & 1st,40.721651,-74.042884,JC023,Brunswick St,40.724176,-74.050656,42419,Subscriber,1988,1
2,269,2021-01-04 13:16:00.9080,2021-01-04 13:20:30.7690,JC082,Manila & 1st,40.721651,-74.042884,JC023,Brunswick St,40.724176,-74.050656,38460,Subscriber,1982,1
3,207,2021-01-05 22:53:03.5880,2021-01-05 22:56:30.7910,JC082,Manila & 1st,40.721651,-74.042884,JC023,Brunswick St,40.724176,-74.050656,47258,Subscriber,1988,1
4,238,2021-01-08 23:10:38.3990,2021-01-08 23:14:36.4990,JC082,Manila & 1st,40.721651,-74.042884,JC023,Brunswick St,40.724176,-74.050656,47257,Subscriber,1988,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11612,104,2021-01-12 07:24:12.2750,2021-01-12 07:25:56.3690,JC065,Dey St,40.737711,-74.066921,JC065,Dey St,40.737711,-74.066921,28364,Subscriber,1966,1
11613,195,2021-01-10 15:25:53.3320,2021-01-10 15:29:09.3190,JC018,5 Corners Library,40.734961,-74.059503,JC065,Dey St,40.737711,-74.066921,28364,Subscriber,1961,1
11614,369,2021-01-12 22:09:16.7860,2021-01-12 22:15:25.9820,JC018,5 Corners Library,40.734961,-74.059503,JC065,Dey St,40.737711,-74.066921,46395,Subscriber,1998,1
11615,341,2021-01-12 22:09:52.5970,2021-01-12 22:15:34.1270,JC018,5 Corners Library,40.734961,-74.059503,JC065,Dey St,40.737711,-74.066921,41547,Customer,1969,0
11616,820,2021-01-19 14:11:14.0330,2021-01-19 14:24:54.8420,JC057,Riverview Park,40.744319,-74.043991,JC065,Dey St,40.737711,-74.066921,44698,Customer,1969,0