In [1]:
import pandas as pd

In [2]:
feb_df = pd.read_csv("/Users/amber/Desktop/GitHub/Tableau-DataClean/csvs/JC-202102-citibike-tripdata.csv")
feb_df

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,121DD7DD23CB1335,docked_bike,2021-02-03 23:11:28,2021-02-03 23:18:28,Hoboken Ave at Monmouth St,JC105,Christ Hospital,JC034,40.735208,-74.046964,40.734786,-74.050444,member
1,FD73FB85F008349D,docked_bike,2021-02-27 16:34:05,2021-02-27 16:56:40,Newport Pkwy,JC008,Marin Light Rail,JC013,40.728744,-74.032108,40.714584,-74.042817,member
2,39F9E6663CB5FDF6,docked_bike,2021-02-26 23:16:04,2021-02-26 23:22:25,Journal Square,JC103,Baldwin at Montgomery,JC020,40.733670,-74.062500,40.723659,-74.064194,member
3,A64745CB0792EC6F,docked_bike,2021-02-24 16:51:50,2021-02-24 17:16:09,Hoboken Ave at Monmouth St,JC105,Hoboken Ave at Monmouth St,JC105,40.735208,-74.046963,40.735208,-74.046964,casual
4,75CC76EB9543764A,docked_bike,2021-02-24 20:44:16,2021-02-24 20:44:46,Hoboken Ave at Monmouth St,JC105,Hoboken Ave at Monmouth St,JC105,40.735208,-74.046963,40.735208,-74.046964,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4876,3F8FD9A051C0E3DA,docked_bike,2021-02-24 18:05:45,2021-02-24 18:12:27,Columbus Drive,JC014,Newport Pkwy,JC008,40.718355,-74.038914,40.728745,-74.032108,member
4877,B91F3593C0C06D04,docked_bike,2021-02-22 18:22:04,2021-02-22 18:28:45,Columbus Drive,JC014,Newport Pkwy,JC008,40.718355,-74.038914,40.728745,-74.032108,member
4878,A790954A017D07CB,docked_bike,2021-02-13 12:21:49,2021-02-13 12:27:51,Columbus Drive,JC014,Newport Pkwy,JC008,40.718355,-74.038914,40.728745,-74.032108,member
4879,42B1932D06CEE034,docked_bike,2021-02-25 11:20:29,2021-02-25 11:25:23,Columbus Drive,JC014,Morris Canal,JC072,40.718355,-74.038914,40.712419,-74.038526,member
4880,F71732ECE7CD02CF,docked_bike,2021-02-19 13:59:22,2021-02-19 14:05:47,Columbus Drive,JC014,Newport Pkwy,JC008,40.718355,-74.038914,40.728745,-74.032108,member

In [3]:
feb_df_station = feb_df.loc[:, 'start_station_name':'start_station_id']
feb_df_station = feb_df_station.drop_duplicates()
feb_df_station.sort_values(by='start_station_id')
feb_df_station.reset_index(drop=True, inplace=True)
feb_df_station.to_csv(r'/Users/amber/Desktop/GitHub/Tableau-DataClean/csvs/start_station_ids.csv', index=False)

In [4]:
feb_df_station_end = feb_df.loc[:, 'end_station_name':'end_station_id']
feb_df_station_end = feb_df_station_end.drop_duplicates()
feb_df_station_end.reset_index(drop=True, inplace=True)
feb_df_station_end.to_csv(r'/Users/amber/Desktop/GitHub/Tableau-DataClean/csvs/end_station_ids.csv', index=False)

In [5]:
feb_df_station.to_dict('list')

{'start_station_name': ['Hoboken Ave at Monmouth St',
  'Newport Pkwy',
  'Journal Square',
  'Newark Ave',
  '5 Corners Library',
  'Washington St',
  'Montgomery St',
  'York St',
  'Marin Light Rail',
  'Morris Canal',
  'Communipaw & Berry Lane',
  'Monmouth and 6th',
  'Baldwin at Montgomery',
  'Liberty Light Rail',
  'Pershing Field',
  'Heights Elevator',
  'Astor Place',
  'Sip Ave',
  'McGinley Square',
  'Jackson Square',
  'Harborside',
  'Paulus Hook',
  'Warren St',
  'Union St',
  'Glenwood Ave',
  'Bergen Ave',
  'Oakland Ave',
  'Hilltop',
  'Jersey & 3rd',
  'JC Medical Center',
  'Newport PATH',
  'Lafayette Park',
  'Brunswick St',
  'Brunswick & 6th',
  'Hamilton Park',
  'Dey St',
  'Riverview Park',
  'Fairmount Ave',
  'Grove St PATH',
  'Grand St',
  'Christ Hospital',
  'Columbus Dr at Exchange Pl',
  'Van Vorst Park',
  'Leonard Gordon Park',
  'Essex Light Rail',
  'Lincoln Park',
  'Manila & 1st',
  'Dixon Mills',
  'City Hall',
  'Jersey & 6th St',
  'Columbus Drive'],
 'start_station_id': ['JC105',
  'JC008',
  'JC103',
  'JC032',
  'JC018',
  'JC098',
  'JC099',
  'JC096',
  'JC013',
  'JC072',
  'JC084',
  'JC075',
  'JC020',
  'JC052',
  'JC024',
  'JC059',
  'JC077',
  'JC056',
  'JC055',
  'JC063',
  'JC104',
  'JC002',
  'JC006',
  'JC051',
  'JC094',
  'JC095',
  'JC022',
  'JC019',
  'JC074',
  'JC011',
  'JC066',
  'JC078',
  'JC023',
  'JC081',
  'JC009',
  'JC065',
  'JC057',
  'JC093',
  'JC005',
  'JC102',
  'JC034',
  'JC106',
  'JC035',
  'JC080',
  'JC038',
  'JC053',
  'JC082',
  'JC076',
  'JC003',
  'JC027',
  'JC014']}

In [6]:
import pandas as pd

jan_df = pd.read_csv("/Users/amber/Desktop/GitHub/Tableau-DataClean/csvs/JC-202101-citibike-tripdata.csv")
jan_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,266,2021-01-01 00:03:35.5100,2021-01-01 00:08:01.7770,3273,Manila & 1st,40.721651,-74.042884,3209,Brunswick St,40.724176,-74.050656,42494,Subscriber,1988,1
1,1543,2021-01-01 00:23:32.9250,2021-01-01 00:49:16.0830,3681,Grand St,40.715178,-74.037683,3213,Van Vorst Park,40.718489,-74.047727,45343,Customer,1996,2
2,1461,2021-01-01 00:23:50.7940,2021-01-01 00:48:12.5660,3681,Grand St,40.715178,-74.037683,3213,Van Vorst Park,40.718489,-74.047727,31794,Customer,1995,1
3,793,2021-01-01 00:31:09.0770,2021-01-01 00:44:22.9430,3185,City Hall,40.717732,-74.043845,3199,Newport Pkwy,40.728745,-74.032108,42316,Customer,1969,0
4,596,2021-01-01 00:35:52.1900,2021-01-01 00:45:48.7740,3639,Harborside,40.719252,-74.034234,3209,Brunswick St,40.724176,-74.050656,32575,Customer,1969,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11619,2476,2021-01-31 20:16:05.4700,2021-01-31 20:57:22.0110,3187,Warren St,40.721124,-74.038051,3483,Montgomery St,40.719420,-74.050990,44852,Subscriber,1958,1
11620,147,2021-01-31 21:05:05.2090,2021-01-31 21:07:32.8660,3186,Grove St PATH,40.719586,-74.043117,3187,Warren St,40.721124,-74.038051,46538,Subscriber,1972,1
11621,660,2021-01-31 21:06:23.5880,2021-01-31 21:17:23.8420,3211,Newark Ave,40.721525,-74.046305,3276,Marin Light Rail,40.714584,-74.042817,44398,Subscriber,1987,2
11622,384,2021-01-31 21:16:37.8220,2021-01-31 21:23:02.1240,3205,JC Medical Center,40.716540,-74.049638,3268,Lafayette Park,40.713464,-74.062859,41400,Subscriber,1989,1
11623,356,2021-01-31 23:24:50.8810,2021-01-31 23:30:47.3030,3639,Harborside,40.719252,-74.034234,3186,Grove St PATH,40.719586,-74.043117,43766,Subscriber,1994,1

In [7]:
jan_df.columns = jan_df.columns.str.replace(' ', '_')
jan_df

,tripduration,starttime,stoptime,start_station_id,start_station_name,start_station_latitude,start_station_longitude,end_station_id,end_station_name,end_station_latitude,end_station_longitude,bikeid,usertype,birth_year,gender
0,266,2021-01-01 00:03:35.5100,2021-01-01 00:08:01.7770,3273,Manila & 1st,40.721651,-74.042884,3209,Brunswick St,40.724176,-74.050656,42494,Subscriber,1988,1
1,1543,2021-01-01 00:23:32.9250,2021-01-01 00:49:16.0830,3681,Grand St,40.715178,-74.037683,3213,Van Vorst Park,40.718489,-74.047727,45343,Customer,1996,2
2,1461,2021-01-01 00:23:50.7940,2021-01-01 00:48:12.5660,3681,Grand St,40.715178,-74.037683,3213,Van Vorst Park,40.718489,-74.047727,31794,Customer,1995,1
3,793,2021-01-01 00:31:09.0770,2021-01-01 00:44:22.9430,3185,City Hall,40.717732,-74.043845,3199,Newport Pkwy,40.728745,-74.032108,42316,Customer,1969,0
4,596,2021-01-01 00:35:52.1900,2021-01-01 00:45:48.7740,3639,Harborside,40.719252,-74.034234,3209,Brunswick St,40.724176,-74.050656,32575,Customer,1969,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11619,2476,2021-01-31 20:16:05.4700,2021-01-31 20:57:22.0110,3187,Warren St,40.721124,-74.038051,3483,Montgomery St,40.719420,-74.050990,44852,Subscriber,1958,1
11620,147,2021-01-31 21:05:05.2090,2021-01-31 21:07:32.8660,3186,Grove St PATH,40.719586,-74.043117,3187,Warren St,40.721124,-74.038051,46538,Subscriber,1972,1
11621,660,2021-01-31 21:06:23.5880,2021-01-31 21:17:23.8420,3211,Newark Ave,40.721525,-74.046305,3276,Marin Light Rail,40.714584,-74.042817,44398,Subscriber,1987,2
11622,384,2021-01-31 21:16:37.8220,2021-01-31 21:23:02.1240,3205,JC Medical Center,40.716540,-74.049638,3268,Lafayette Park,40.713464,-74.062859,41400,Subscriber,1989,1
11623,356,2021-01-31 23:24:50.8810,2021-01-31 23:30:47.3030,3639,Harborside,40.719252,-74.034234,3186,Grove St PATH,40.719586,-74.043117,43766,Subscriber,1994,1

In [8]:
new_jan_df = pd.merge(jan_df, feb_df_station, on='start_station_name')
new_jan_df

,tripduration,starttime,stoptime,start_station_id_x,start_station_name,start_station_latitude,start_station_longitude,end_station_id,end_station_name,end_station_latitude,end_station_longitude,bikeid,usertype,birth_year,gender,start_station_id_y
0,266,2021-01-01 00:03:35.5100,2021-01-01 00:08:01.7770,3273,Manila & 1st,40.721651,-74.042884,3209,Brunswick St,40.724176,-74.050656,42494,Subscriber,1988,1,JC082
1,1710,2021-01-01 14:47:19.7140,2021-01-01 15:15:50.6870,3273,Manila & 1st,40.721651,-74.042884,3185,City Hall,40.717732,-74.043845,42422,Subscriber,1969,1,JC082
2,374,2021-01-02 09:18:47.6460,2021-01-02 09:25:02.0330,3273,Manila & 1st,40.721651,-74.042884,3270,Jersey & 6th St,40.725289,-74.045572,40464,Subscriber,1987,1,JC082
3,239,2021-01-02 10:05:45.8090,2021-01-02 10:09:45.3650,3273,Manila & 1st,40.721651,-74.042884,3203,Hamilton Park,40.727596,-74.044247,42368,Subscriber,1981,1,JC082
4,250,2021-01-02 11:45:06.8420,2021-01-02 11:49:17.1970,3273,Manila & 1st,40.721651,-74.042884,3638,Washington St,40.724294,-74.035483,45364,Subscriber,1988,2,JC082
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11619,2322,2021-01-28 12:47:43.6810,2021-01-28 13:26:26.0380,3196,Riverview Park,40.744319,-74.043991,3195,Sip Ave,40.730897,-74.063913,43361,Subscriber,1998,2,JC057
11620,1285,2021-01-28 14:44:09.1600,2021-01-28 15:05:34.3550,3196,Riverview Park,40.744319,-74.043991,3273,Manila & 1st,40.721651,-74.042884,44376,Subscriber,1968,1,JC057
11621,549,2021-01-29 19:42:20.8910,2021-01-29 19:51:29.9640,3196,Riverview Park,40.744319,-74.043991,3196,Riverview Park,40.744319,-74.043991,40954,Subscriber,1998,2,JC057
11622,562,2021-01-30 12:00:28.5500,2021-01-30 12:09:51.3200,3196,Riverview Park,40.744319,-74.043991,3269,Brunswick & 6th,40.726012,-74.050389,40954,Customer,1996,1,JC057
11623,990,2021-01-30 16:08:19.5370,2021-01-30 16:24:50.3170,3196,Riverview Park,40.744319,-74.043991,3187,Warren St,40.721124,-74.038051,39329,Subscriber,1988,1,JC057

In [9]:
new_jan_df = pd.merge(new_jan_df, feb_df_station_end, on='end_station_name')
new_jan_df

,tripduration,starttime,stoptime,start_station_id_x,start_station_name,start_station_latitude,start_station_longitude,end_station_id_x,end_station_name,end_station_latitude,end_station_longitude,bikeid,usertype,birth_year,gender,start_station_id_y,end_station_id_y
0,266,2021-01-01 00:03:35.5100,2021-01-01 00:08:01.7770,3273,Manila & 1st,40.721651,-74.042884,3209,Brunswick St,40.724176,-74.050656,42494,Subscriber,1988,1,JC082,JC023
1,296,2021-01-02 23:16:11.3820,2021-01-02 23:21:08.3150,3273,Manila & 1st,40.721651,-74.042884,3209,Brunswick St,40.724176,-74.050656,42419,Subscriber,1988,1,JC082,JC023
2,269,2021-01-04 13:16:00.9080,2021-01-04 13:20:30.7690,3273,Manila & 1st,40.721651,-74.042884,3209,Brunswick St,40.724176,-74.050656,38460,Subscriber,1982,1,JC082,JC023
3,207,2021-01-05 22:53:03.5880,2021-01-05 22:56:30.7910,3273,Manila & 1st,40.721651,-74.042884,3209,Brunswick St,40.724176,-74.050656,47258,Subscriber,1988,1,JC082,JC023
4,238,2021-01-08 23:10:38.3990,2021-01-08 23:14:36.4990,3273,Manila & 1st,40.721651,-74.042884,3209,Brunswick St,40.724176,-74.050656,47257,Subscriber,1988,1,JC082,JC023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11612,104,2021-01-12 07:24:12.2750,2021-01-12 07:25:56.3690,3201,Dey St,40.737711,-74.066921,3201,Dey St,40.737711,-74.066921,28364,Subscriber,1966,1,JC065,JC065
11613,195,2021-01-10 15:25:53.3320,2021-01-10 15:29:09.3190,3220,5 Corners Library,40.734961,-74.059503,3201,Dey St,40.737711,-74.066921,28364,Subscriber,1961,1,JC018,JC065
11614,369,2021-01-12 22:09:16.7860,2021-01-12 22:15:25.9820,3220,5 Corners Library,40.734961,-74.059503,3201,Dey St,40.737711,-74.066921,46395,Subscriber,1998,1,JC018,JC065
11615,341,2021-01-12 22:09:52.5970,2021-01-12 22:15:34.1270,3220,5 Corners Library,40.734961,-74.059503,3201,Dey St,40.737711,-74.066921,41547,Customer,1969,0,JC018,JC065
11616,820,2021-01-19 14:11:14.0330,2021-01-19 14:24:54.8420,3196,Riverview Park,40.744319,-74.043991,3201,Dey St,40.737711,-74.066921,44698,Customer,1969,0,JC057,JC065

In [10]:
new_jan_df.drop(columns=['start_station_id_x', 'end_station_id_x'], inplace=True)
new_jan_df

,tripduration,starttime,stoptime,start_station_name,start_station_latitude,start_station_longitude,end_station_name,end_station_latitude,end_station_longitude,bikeid,usertype,birth_year,gender,start_station_id_y,end_station_id_y
0,266,2021-01-01 00:03:35.5100,2021-01-01 00:08:01.7770,Manila & 1st,40.721651,-74.042884,Brunswick St,40.724176,-74.050656,42494,Subscriber,1988,1,JC082,JC023
1,296,2021-01-02 23:16:11.3820,2021-01-02 23:21:08.3150,Manila & 1st,40.721651,-74.042884,Brunswick St,40.724176,-74.050656,42419,Subscriber,1988,1,JC082,JC023
2,269,2021-01-04 13:16:00.9080,2021-01-04 13:20:30.7690,Manila & 1st,40.721651,-74.042884,Brunswick St,40.724176,-74.050656,38460,Subscriber,1982,1,JC082,JC023
3,207,2021-01-05 22:53:03.5880,2021-01-05 22:56:30.7910,Manila & 1st,40.721651,-74.042884,Brunswick St,40.724176,-74.050656,47258,Subscriber,1988,1,JC082,JC023
4,238,2021-01-08 23:10:38.3990,2021-01-08 23:14:36.4990,Manila & 1st,40.721651,-74.042884,Brunswick St,40.724176,-74.050656,47257,Subscriber,1988,1,JC082,JC023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11612,104,2021-01-12 07:24:12.2750,2021-01-12 07:25:56.3690,Dey St,40.737711,-74.066921,Dey St,40.737711,-74.066921,28364,Subscriber,1966,1,JC065,JC065
11613,195,2021-01-10 15:25:53.3320,2021-01-10 15:29:09.3190,5 Corners Library,40.734961,-74.059503,Dey St,40.737711,-74.066921,28364,Subscriber,1961,1,JC018,JC065
11614,369,2021-01-12 22:09:16.7860,2021-01-12 22:15:25.9820,5 Corners Library,40.734961,-74.059503,Dey St,40.737711,-74.066921,46395,Subscriber,1998,1,JC018,JC065
11615,341,2021-01-12 22:09:52.5970,2021-01-12 22:15:34.1270,5 Corners Library,40.734961,-74.059503,Dey St,40.737711,-74.066921,41547,Customer,1969,0,JC018,JC065
11616,820,2021-01-19 14:11:14.0330,2021-01-19 14:24:54.8420,Riverview Park,40.744319,-74.043991,Dey St,40.737711,-74.066921,44698,Customer,1969,0,JC057,JC065

In [11]:
new_jan_df.rename(columns = {'start_station_id_y':'start_station_id', 'end_station_id_y':'end_station_id'}, inplace=True)
new_jan_df

,tripduration,starttime,stoptime,start_station_name,start_station_latitude,start_station_longitude,end_station_name,end_station_latitude,end_station_longitude,bikeid,usertype,birth_year,gender,start_station_id,end_station_id
0,266,2021-01-01 00:03:35.5100,2021-01-01 00:08:01.7770,Manila & 1st,40.721651,-74.042884,Brunswick St,40.724176,-74.050656,42494,Subscriber,1988,1,JC082,JC023
1,296,2021-01-02 23:16:11.3820,2021-01-02 23:21:08.3150,Manila & 1st,40.721651,-74.042884,Brunswick St,40.724176,-74.050656,42419,Subscriber,1988,1,JC082,JC023
2,269,2021-01-04 13:16:00.9080,2021-01-04 13:20:30.7690,Manila & 1st,40.721651,-74.042884,Brunswick St,40.724176,-74.050656,38460,Subscriber,1982,1,JC082,JC023
3,207,2021-01-05 22:53:03.5880,2021-01-05 22:56:30.7910,Manila & 1st,40.721651,-74.042884,Brunswick St,40.724176,-74.050656,47258,Subscriber,1988,1,JC082,JC023
4,238,2021-01-08 23:10:38.3990,2021-01-08 23:14:36.4990,Manila & 1st,40.721651,-74.042884,Brunswick St,40.724176,-74.050656,47257,Subscriber,1988,1,JC082,JC023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11612,104,2021-01-12 07:24:12.2750,2021-01-12 07:25:56.3690,Dey St,40.737711,-74.066921,Dey St,40.737711,-74.066921,28364,Subscriber,1966,1,JC065,JC065
11613,195,2021-01-10 15:25:53.3320,2021-01-10 15:29:09.3190,5 Corners Library,40.734961,-74.059503,Dey St,40.737711,-74.066921,28364,Subscriber,1961,1,JC018,JC065
11614,369,2021-01-12 22:09:16.7860,2021-01-12 22:15:25.9820,5 Corners Library,40.734961,-74.059503,Dey St,40.737711,-74.066921,46395,Subscriber,1998,1,JC018,JC065
11615,341,2021-01-12 22:09:52.5970,2021-01-12 22:15:34.1270,5 Corners Library,40.734961,-74.059503,Dey St,40.737711,-74.066921,41547,Customer,1969,0,JC018,JC065
11616,820,2021-01-19 14:11:14.0330,2021-01-19 14:24:54.8420,Riverview Park,40.744319,-74.043991,Dey St,40.737711,-74.066921,44698,Customer,1969,0,JC057,JC065

In [12]:
new_jan_df = new_jan_df.reindex(columns=['tripduration', 'starttime', 'stoptime', 'start_station_id', 'start_station_name', 'start_station_latitude', 'start_station_longitude', 'end_station_id', 'end_station_name', 'end_station_latitude', 'end_station_longitude', 'bikeid', 'usertype', 'birth_year', 'gender'])
new_jan_df.to_csv(r'/Users/amber/Desktop/GitHub/Tableau-DataClean/csvs/JC-202101-citibike-tripdata-CLEANED.csv', index=False)
new_jan_df

,tripduration,starttime,stoptime,start_station_id,start_station_name,start_station_latitude,start_station_longitude,end_station_id,end_station_name,end_station_latitude,end_station_longitude,bikeid,usertype,birth_year,gender
0,266,2021-01-01 00:03:35.5100,2021-01-01 00:08:01.7770,JC082,Manila & 1st,40.721651,-74.042884,JC023,Brunswick St,40.724176,-74.050656,42494,Subscriber,1988,1
1,296,2021-01-02 23:16:11.3820,2021-01-02 23:21:08.3150,JC082,Manila & 1st,40.721651,-74.042884,JC023,Brunswick St,40.724176,-74.050656,42419,Subscriber,1988,1
2,269,2021-01-04 13:16:00.9080,2021-01-04 13:20:30.7690,JC082,Manila & 1st,40.721651,-74.042884,JC023,Brunswick St,40.724176,-74.050656,38460,Subscriber,1982,1
3,207,2021-01-05 22:53:03.5880,2021-01-05 22:56:30.7910,JC082,Manila & 1st,40.721651,-74.042884,JC023,Brunswick St,40.724176,-74.050656,47258,Subscriber,1988,1
4,238,2021-01-08 23:10:38.3990,2021-01-08 23:14:36.4990,JC082,Manila & 1st,40.721651,-74.042884,JC023,Brunswick St,40.724176,-74.050656,47257,Subscriber,1988,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11612,104,2021-01-12 07:24:12.2750,2021-01-12 07:25:56.3690,JC065,Dey St,40.737711,-74.066921,JC065,Dey St,40.737711,-74.066921,28364,Subscriber,1966,1
11613,195,2021-01-10 15:25:53.3320,2021-01-10 15:29:09.3190,JC018,5 Corners Library,40.734961,-74.059503,JC065,Dey St,40.737711,-74.066921,28364,Subscriber,1961,1
11614,369,2021-01-12 22:09:16.7860,2021-01-12 22:15:25.9820,JC018,5 Corners Library,40.734961,-74.059503,JC065,Dey St,40.737711,-74.066921,46395,Subscriber,1998,1
11615,341,2021-01-12 22:09:52.5970,2021-01-12 22:15:34.1270,JC018,5 Corners Library,40.734961,-74.059503,JC065,Dey St,40.737711,-74.066921,41547,Customer,1969,0
11616,820,2021-01-19 14:11:14.0330,2021-01-19 14:24:54.8420,JC057,Riverview Park,40.744319,-74.043991,JC065,Dey St,40.737711,-74.066921,44698,Customer,1969,0

In [13]:
# Updating usertype to match Feb-Jun data -- making assumption that Subscriber = Member and Customer = Casual
new_jan_df['usertype'] = new_jan_df['usertype'].replace(['Subscriber','Customer'], ['member', 'casual'])
new_jan_df

,tripduration,starttime,stoptime,start_station_id,start_station_name,start_station_latitude,start_station_longitude,end_station_id,end_station_name,end_station_latitude,end_station_longitude,bikeid,usertype,birth_year,gender
0,266,2021-01-01 00:03:35.5100,2021-01-01 00:08:01.7770,JC082,Manila & 1st,40.721651,-74.042884,JC023,Brunswick St,40.724176,-74.050656,42494,member,1988,1
1,296,2021-01-02 23:16:11.3820,2021-01-02 23:21:08.3150,JC082,Manila & 1st,40.721651,-74.042884,JC023,Brunswick St,40.724176,-74.050656,42419,member,1988,1
2,269,2021-01-04 13:16:00.9080,2021-01-04 13:20:30.7690,JC082,Manila & 1st,40.721651,-74.042884,JC023,Brunswick St,40.724176,-74.050656,38460,member,1982,1
3,207,2021-01-05 22:53:03.5880,2021-01-05 22:56:30.7910,JC082,Manila & 1st,40.721651,-74.042884,JC023,Brunswick St,40.724176,-74.050656,47258,member,1988,1
4,238,2021-01-08 23:10:38.3990,2021-01-08 23:14:36.4990,JC082,Manila & 1st,40.721651,-74.042884,JC023,Brunswick St,40.724176,-74.050656,47257,member,1988,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11612,104,2021-01-12 07:24:12.2750,2021-01-12 07:25:56.3690,JC065,Dey St,40.737711,-74.066921,JC065,Dey St,40.737711,-74.066921,28364,member,1966,1
11613,195,2021-01-10 15:25:53.3320,2021-01-10 15:29:09.3190,JC018,5 Corners Library,40.734961,-74.059503,JC065,Dey St,40.737711,-74.066921,28364,member,1961,1
11614,369,2021-01-12 22:09:16.7860,2021-01-12 22:15:25.9820,JC018,5 Corners Library,40.734961,-74.059503,JC065,Dey St,40.737711,-74.066921,46395,member,1998,1
11615,341,2021-01-12 22:09:52.5970,2021-01-12 22:15:34.1270,JC018,5 Corners Library,40.734961,-74.059503,JC065,Dey St,40.737711,-74.066921,41547,casual,1969,0
11616,820,2021-01-19 14:11:14.0330,2021-01-19 14:24:54.8420,JC057,Riverview Park,40.744319,-74.043991,JC065,Dey St,40.737711,-74.066921,44698,casual,1969,0

In [14]:
list(feb_df)
new_jan_df.rename(columns={'starttime':'started_at', 'stoptime':'ended_at', 'start_station_latitude':'start_lat', 'start_station_longitude':'start_lng', 'end_station_latitude':'end_lat', 'end_station_longitude':'end_lng', 'usertype':'member_casual'})
new_jan_df.to_csv(r'/Users/amber/Desktop/GitHub/Tableau-DataClean/csvs/JC-202101-citibike-tripdata-CLEANED.csv', index=False)

In [15]:
mar_df = pd.read_csv("/Users/amber/Desktop/GitHub/Tableau-DataClean/csvs/JC-202103-citibike-tripdata.csv")
mar_df

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,ABBBB4D89C620898,docked_bike,2021-03-03 10:32:07,2021-03-03 10:32:40,Jackson Square,JC063,Jackson Square,JC063,40.711130,-74.078900,40.711130,-74.078900,member
1,987BC8C414C77F3E,docked_bike,2021-03-14 00:21:37,2021-03-14 00:22:59,Jackson Square,JC063,Jackson Square,JC063,40.711130,-74.078900,40.711130,-74.078900,casual
2,342C5C515F0F8BCB,docked_bike,2021-03-21 14:39:46,2021-03-21 15:33:10,Jackson Square,JC063,Warren St,JC006,40.711130,-74.078900,40.721124,-74.038051,casual
3,AB28945141163E31,docked_bike,2021-03-14 00:27:21,2021-03-14 00:31:07,Jackson Square,JC063,Jackson Square,JC063,40.711130,-74.078900,40.711130,-74.078900,casual
4,4F5758803BC3DE72,docked_bike,2021-03-12 20:45:29,2021-03-13 08:58:59,Jackson Square,JC063,Jackson Square,JC063,40.711130,-74.078900,40.711130,-74.078900,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
17118,6749C4D091AAA8CA,docked_bike,2021-03-29 19:30:20,2021-03-29 19:38:10,Harborside,JC104,Morris Canal,JC072,40.719251,-74.034234,40.712419,-74.038526,member
17119,3DBAB9D9FA2758A3,docked_bike,2021-03-12 18:49:06,2021-03-12 18:54:35,Harborside,JC104,Morris Canal,JC072,40.719251,-74.034234,40.712419,-74.038526,member
17120,E0183D5DD0C62E12,docked_bike,2021-03-28 12:29:15,2021-03-28 12:34:40,Harborside,JC104,Newark Ave,JC032,40.719251,-74.034234,40.721525,-74.046305,member
17121,D39E4D9D8F735AB8,docked_bike,2021-03-23 13:03:35,2021-03-23 13:10:25,Harborside,JC104,Newark Ave,JC032,40.719251,-74.034234,40.721525,-74.046305,member
17122,87D47774A82633A6,docked_bike,2021-03-24 10:12:54,2021-03-24 10:21:17,Harborside,JC104,Newark Ave,JC032,40.719251,-74.034234,40.721525,-74.046305,member

In [21]:
feb_mar_df = pd.concat([feb_df, mar_df]).reset_index(drop=True)
feb_mar_df.to_csv(r'/Users/amber/Desktop/GitHub/Tableau-DataClean/csvs/FEB-MAR-citibike-tripdata.csv', index=False)
feb_mar_df

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,121DD7DD23CB1335,docked_bike,2021-02-03 23:11:28,2021-02-03 23:18:28,Hoboken Ave at Monmouth St,JC105,Christ Hospital,JC034,40.735208,-74.046964,40.734786,-74.050444,member
1,FD73FB85F008349D,docked_bike,2021-02-27 16:34:05,2021-02-27 16:56:40,Newport Pkwy,JC008,Marin Light Rail,JC013,40.728744,-74.032108,40.714584,-74.042817,member
2,39F9E6663CB5FDF6,docked_bike,2021-02-26 23:16:04,2021-02-26 23:22:25,Journal Square,JC103,Baldwin at Montgomery,JC020,40.733670,-74.062500,40.723659,-74.064194,member
3,A64745CB0792EC6F,docked_bike,2021-02-24 16:51:50,2021-02-24 17:16:09,Hoboken Ave at Monmouth St,JC105,Hoboken Ave at Monmouth St,JC105,40.735208,-74.046963,40.735208,-74.046964,casual
4,75CC76EB9543764A,docked_bike,2021-02-24 20:44:16,2021-02-24 20:44:46,Hoboken Ave at Monmouth St,JC105,Hoboken Ave at Monmouth St,JC105,40.735208,-74.046963,40.735208,-74.046964,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
21999,6749C4D091AAA8CA,docked_bike,2021-03-29 19:30:20,2021-03-29 19:38:10,Harborside,JC104,Morris Canal,JC072,40.719251,-74.034234,40.712419,-74.038526,member
22000,3DBAB9D9FA2758A3,docked_bike,2021-03-12 18:49:06,2021-03-12 18:54:35,Harborside,JC104,Morris Canal,JC072,40.719251,-74.034234,40.712419,-74.038526,member
22001,E0183D5DD0C62E12,docked_bike,2021-03-28 12:29:15,2021-03-28 12:34:40,Harborside,JC104,Newark Ave,JC032,40.719251,-74.034234,40.721525,-74.046305,member
22002,D39E4D9D8F735AB8,docked_bike,2021-03-23 13:03:35,2021-03-23 13:10:25,Harborside,JC104,Newark Ave,JC032,40.719251,-74.034234,40.721525,-74.046305,member
22003,87D47774A82633A6,docked_bike,2021-03-24 10:12:54,2021-03-24 10:21:17,Harborside,JC104,Newark Ave,JC032,40.719251,-74.034234,40.721525,-74.046305,member

In [18]:
apr_df = pd.read_csv("/Users/amber/Desktop/GitHub/Tableau-DataClean/csvs/JC-202104-citibike-tripdata.csv")
apr_df

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,8B8A826EA1FB6246,docked_bike,2021-04-02 18:06:51,2021-04-02 18:42:17,Paulus Hook,JC002,Astor Place,JC077,40.714145,-74.033551,40.719282,-74.071262,member
1,6ECB53933BB5424E,docked_bike,2021-04-06 21:19:27,2021-04-06 21:59:56,Bergen Ave,JC095,Bergen Ave,JC095,40.722103,-74.071455,40.722104,-74.071455,casual
2,DC8E726CDD4A3FDE,docked_bike,2021-04-07 17:26:47,2021-04-07 17:31:01,Bergen Ave,JC095,Lincoln Park,JC053,40.722103,-74.071455,40.724605,-74.078406,member
3,CDBF0A93464AB439,docked_bike,2021-04-30 20:23:42,2021-04-30 20:32:12,Jersey & 6th St,JC027,Hoboken Ave at Monmouth St,JC105,40.725289,-74.045571,40.735208,-74.046964,casual
4,7AC523690FC1E82E,docked_bike,2021-04-23 18:48:11,2021-04-23 18:57:29,Paulus Hook,JC002,Washington St,JC098,40.714145,-74.033551,40.724294,-74.035483,casual
...,...,...,...,...,...,...,...,...,...,...,...,...,...
23769,BEB399F6639BF799,docked_bike,2021-04-28 20:51:53,2021-04-28 20:53:38,Fairmount Ave,JC093,McGinley Square,JC055,40.725726,-74.071959,40.725340,-74.067622,member
23770,A4C1021E7C9EE4E3,docked_bike,2021-04-14 06:34:16,2021-04-14 06:44:53,Fairmount Ave,JC093,Grand St,JC102,40.725726,-74.071959,40.715178,-74.037683,member
23771,3EA6DA6311CFDE83,docked_bike,2021-04-09 12:33:19,2021-04-09 12:38:58,Van Vorst Park,JC035,Grand St,JC102,40.718489,-74.047727,40.715178,-74.037683,member
23772,3F0B6BDE42FE6B6E,docked_bike,2021-04-09 08:25:38,2021-04-09 08:31:21,Van Vorst Park,JC035,Grand St,JC102,40.718488,-74.047726,40.715178,-74.037683,member
23773,2E52C2BD921E2C26,docked_bike,2021-04-09 05:49:06,2021-04-09 06:06:13,Brunswick & 6th,JC081,Heights Elevator,JC059,40.726011,-74.050388,40.748716,-74.040443,casual

In [19]:
may_df = pd.read_csv("/Users/amber/Desktop/GitHub/Tableau-DataClean/csvs/JC-202105-citibike-tripdata.csv")
may_df

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,74A4206E7487CBC9,docked_bike,2021-05-23 16:51:00,2021-05-23 18:38:21,9 St HBLR - Jackson St & 8 St,HB305,9 St HBLR - Jackson St & 8 St,HB305,40.747907,-74.038411,40.747907,-74.038412,casual
1,58EEE2950FFE01CE,docked_bike,2021-05-31 16:54:47,2021-05-31 16:55:28,9 St HBLR - Jackson St & 8 St,HB305,9 St HBLR - Jackson St & 8 St,HB305,40.747907,-74.038411,40.747907,-74.038412,member
2,1429D912C16EEE59,docked_bike,2021-05-25 16:19:34,2021-05-25 17:03:06,9 St HBLR - Jackson St & 8 St,HB305,9 St HBLR - Jackson St & 8 St,HB305,40.747907,-74.038411,40.747907,-74.038412,casual
3,FE9C5B74167CBCCD,docked_bike,2021-05-22 17:32:19,2021-05-22 17:41:27,9 St HBLR - Jackson St & 8 St,HB305,Grand St & 2 St,HB405,40.747907,-74.038411,40.739130,-74.036180,casual
4,B88D37626F000BBA,docked_bike,2021-05-14 09:48:34,2021-05-14 10:17:36,Union St,JC051,Newark Ave,JC032,40.718211,-74.083639,40.721525,-74.046305,casual
...,...,...,...,...,...,...,...,...,...,...,...,...,...
45038,62FF3FEDAAD7FCB3,docked_bike,2021-05-31 12:46:22,2021-05-31 12:52:29,Clinton St & 7 St,HB303,7 St & Monroe St,HB304,40.745420,-74.033320,40.746413,-74.037977,casual
45039,E742AEA7068E0E4A,docked_bike,2021-05-31 16:34:19,2021-05-31 16:59:21,Clinton St & 7 St,HB303,Clinton St & 7 St,HB303,40.745420,-74.033320,40.745420,-74.033320,casual
45040,E769F9EE96D6433A,docked_bike,2021-05-17 22:52:35,2021-05-17 23:13:37,Astor Place,JC077,Astor Place,JC077,40.719282,-74.071261,40.719282,-74.071262,casual
45041,EC973614DCA179A2,docked_bike,2021-05-31 20:48:58,2021-05-31 21:16:02,Clinton St & 7 St,HB303,Clinton St & 7 St,HB303,40.745420,-74.033320,40.745420,-74.033320,casual
45042,3571180FE5C52CB1,docked_bike,2021-05-23 14:28:43,2021-05-23 14:30:59,Clinton St & 7 St,HB303,Clinton St & 7 St,HB303,40.745420,-74.033320,40.745420,-74.033320,casual

In [20]:
apr_may_df = pd.concat([apr_df, may_df]).reset_index(drop=True)
apr_may_df.to_csv(r'/Users/amber/Desktop/GitHub/Tableau-DataClean/csvs/APR-MAY-citibike-tripdata.csv', index=False)
apr_may_df

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,8B8A826EA1FB6246,docked_bike,2021-04-02 18:06:51,2021-04-02 18:42:17,Paulus Hook,JC002,Astor Place,JC077,40.714145,-74.033551,40.719282,-74.071262,member
1,6ECB53933BB5424E,docked_bike,2021-04-06 21:19:27,2021-04-06 21:59:56,Bergen Ave,JC095,Bergen Ave,JC095,40.722103,-74.071455,40.722104,-74.071455,casual
2,DC8E726CDD4A3FDE,docked_bike,2021-04-07 17:26:47,2021-04-07 17:31:01,Bergen Ave,JC095,Lincoln Park,JC053,40.722103,-74.071455,40.724605,-74.078406,member
3,CDBF0A93464AB439,docked_bike,2021-04-30 20:23:42,2021-04-30 20:32:12,Jersey & 6th St,JC027,Hoboken Ave at Monmouth St,JC105,40.725289,-74.045571,40.735208,-74.046964,casual
4,7AC523690FC1E82E,docked_bike,2021-04-23 18:48:11,2021-04-23 18:57:29,Paulus Hook,JC002,Washington St,JC098,40.714145,-74.033551,40.724294,-74.035483,casual
...,...,...,...,...,...,...,...,...,...,...,...,...,...
68812,62FF3FEDAAD7FCB3,docked_bike,2021-05-31 12:46:22,2021-05-31 12:52:29,Clinton St & 7 St,HB303,7 St & Monroe St,HB304,40.745420,-74.033320,40.746413,-74.037977,casual
68813,E742AEA7068E0E4A,docked_bike,2021-05-31 16:34:19,2021-05-31 16:59:21,Clinton St & 7 St,HB303,Clinton St & 7 St,HB303,40.745420,-74.033320,40.745420,-74.033320,casual
68814,E769F9EE96D6433A,docked_bike,2021-05-17 22:52:35,2021-05-17 23:13:37,Astor Place,JC077,Astor Place,JC077,40.719282,-74.071261,40.719282,-74.071262,casual
68815,EC973614DCA179A2,docked_bike,2021-05-31 20:48:58,2021-05-31 21:16:02,Clinton St & 7 St,HB303,Clinton St & 7 St,HB303,40.745420,-74.033320,40.745420,-74.033320,casual
68816,3571180FE5C52CB1,docked_bike,2021-05-23 14:28:43,2021-05-23 14:30:59,Clinton St & 7 St,HB303,Clinton St & 7 St,HB303,40.745420,-74.033320,40.745420,-74.033320,casual