In [364]:
# Import pandas

import pandas as pd

In [365]:
# Read Feb csv for data format to match Jan to and pull station IDs

feb_df = pd.read_csv("/Users/amber/Desktop/GitHub/Tableau-DataClean/csvs/JC-202102-citibike-tripdata.csv")
feb_df

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,121DD7DD23CB1335,docked_bike,2021-02-03 23:11:28,2021-02-03 23:18:28,Hoboken Ave at Monmouth St,JC105,Christ Hospital,JC034,40.735208,-74.046964,40.734786,-74.050444,member
1,FD73FB85F008349D,docked_bike,2021-02-27 16:34:05,2021-02-27 16:56:40,Newport Pkwy,JC008,Marin Light Rail,JC013,40.728744,-74.032108,40.714584,-74.042817,member
2,39F9E6663CB5FDF6,docked_bike,2021-02-26 23:16:04,2021-02-26 23:22:25,Journal Square,JC103,Baldwin at Montgomery,JC020,40.733670,-74.062500,40.723659,-74.064194,member
3,A64745CB0792EC6F,docked_bike,2021-02-24 16:51:50,2021-02-24 17:16:09,Hoboken Ave at Monmouth St,JC105,Hoboken Ave at Monmouth St,JC105,40.735208,-74.046963,40.735208,-74.046964,casual
4,75CC76EB9543764A,docked_bike,2021-02-24 20:44:16,2021-02-24 20:44:46,Hoboken Ave at Monmouth St,JC105,Hoboken Ave at Monmouth St,JC105,40.735208,-74.046963,40.735208,-74.046964,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4876,3F8FD9A051C0E3DA,docked_bike,2021-02-24 18:05:45,2021-02-24 18:12:27,Columbus Drive,JC014,Newport Pkwy,JC008,40.718355,-74.038914,40.728745,-74.032108,member
4877,B91F3593C0C06D04,docked_bike,2021-02-22 18:22:04,2021-02-22 18:28:45,Columbus Drive,JC014,Newport Pkwy,JC008,40.718355,-74.038914,40.728745,-74.032108,member
4878,A790954A017D07CB,docked_bike,2021-02-13 12:21:49,2021-02-13 12:27:51,Columbus Drive,JC014,Newport Pkwy,JC008,40.718355,-74.038914,40.728745,-74.032108,member
4879,42B1932D06CEE034,docked_bike,2021-02-25 11:20:29,2021-02-25 11:25:23,Columbus Drive,JC014,Morris Canal,JC072,40.718355,-74.038914,40.712419,-74.038526,member
4880,F71732ECE7CD02CF,docked_bike,2021-02-19 13:59:22,2021-02-19 14:05:47,Columbus Drive,JC014,Newport Pkwy,JC008,40.718355,-74.038914,40.728745,-74.032108,member

In [366]:
# Pull start station IDs and Names

feb_df_station = feb_df.loc[:, 'start_station_name':'start_station_id']
feb_df_station = feb_df_station.drop_duplicates()
feb_df_station.sort_values(by='start_station_id')
feb_df_station.reset_index(drop=True, inplace=True)
feb_df_station.to_csv(r'/Users/amber/Desktop/GitHub/Tableau-DataClean/csvs/start_station_ids.csv', index=False)

In [367]:
# Pull end station IDs and Names

feb_df_station_end = feb_df.loc[:, 'end_station_name':'end_station_id']
feb_df_station_end = feb_df_station_end.drop_duplicates()
feb_df_station_end.reset_index(drop=True, inplace=True)
feb_df_station_end.to_csv(r'/Users/amber/Desktop/GitHub/Tableau-DataClean/csvs/end_station_ids.csv', index=False)

In [368]:
feb_df_station.to_dict('list')

{'start_station_name': ['Hoboken Ave at Monmouth St',
  'Newport Pkwy',
  'Journal Square',
  'Newark Ave',
  '5 Corners Library',
  'Washington St',
  'Montgomery St',
  'York St',
  'Marin Light Rail',
  'Morris Canal',
  'Communipaw & Berry Lane',
  'Monmouth and 6th',
  'Baldwin at Montgomery',
  'Liberty Light Rail',
  'Pershing Field',
  'Heights Elevator',
  'Astor Place',
  'Sip Ave',
  'McGinley Square',
  'Jackson Square',
  'Harborside',
  'Paulus Hook',
  'Warren St',
  'Union St',
  'Glenwood Ave',
  'Bergen Ave',
  'Oakland Ave',
  'Hilltop',
  'Jersey & 3rd',
  'JC Medical Center',
  'Newport PATH',
  'Lafayette Park',
  'Brunswick St',
  'Brunswick & 6th',
  'Hamilton Park',
  'Dey St',
  'Riverview Park',
  'Fairmount Ave',
  'Grove St PATH',
  'Grand St',
  'Christ Hospital',
  'Columbus Dr at Exchange Pl',
  'Van Vorst Park',
  'Leonard Gordon Park',
  'Essex Light Rail',
  'Lincoln Park',
  'Manila & 1st',
  'Dixon Mills',
  'City Hall',
  'Jersey & 6th St',
  'Columbus Drive'],
 'start_station_id': ['JC105',
  'JC008',
  'JC103',
  'JC032',
  'JC018',
  'JC098',
  'JC099',
  'JC096',
  'JC013',
  'JC072',
  'JC084',
  'JC075',
  'JC020',
  'JC052',
  'JC024',
  'JC059',
  'JC077',
  'JC056',
  'JC055',
  'JC063',
  'JC104',
  'JC002',
  'JC006',
  'JC051',
  'JC094',
  'JC095',
  'JC022',
  'JC019',
  'JC074',
  'JC011',
  'JC066',
  'JC078',
  'JC023',
  'JC081',
  'JC009',
  'JC065',
  'JC057',
  'JC093',
  'JC005',
  'JC102',
  'JC034',
  'JC106',
  'JC035',
  'JC080',
  'JC038',
  'JC053',
  'JC082',
  'JC076',
  'JC003',
  'JC027',
  'JC014']}

In [369]:
# Read in Jan data to clean

import pandas as pd

jan_df = pd.read_csv("/Users/amber/Desktop/GitHub/Tableau-DataClean/csvs/JC-202101-citibike-tripdata.csv")
jan_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,266,2021-01-01 00:03:35.5100,2021-01-01 00:08:01.7770,3273,Manila & 1st,40.721651,-74.042884,3209,Brunswick St,40.724176,-74.050656,42494,Subscriber,1988,1
1,1543,2021-01-01 00:23:32.9250,2021-01-01 00:49:16.0830,3681,Grand St,40.715178,-74.037683,3213,Van Vorst Park,40.718489,-74.047727,45343,Customer,1996,2
2,1461,2021-01-01 00:23:50.7940,2021-01-01 00:48:12.5660,3681,Grand St,40.715178,-74.037683,3213,Van Vorst Park,40.718489,-74.047727,31794,Customer,1995,1
3,793,2021-01-01 00:31:09.0770,2021-01-01 00:44:22.9430,3185,City Hall,40.717732,-74.043845,3199,Newport Pkwy,40.728745,-74.032108,42316,Customer,1969,0
4,596,2021-01-01 00:35:52.1900,2021-01-01 00:45:48.7740,3639,Harborside,40.719252,-74.034234,3209,Brunswick St,40.724176,-74.050656,32575,Customer,1969,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11619,2476,2021-01-31 20:16:05.4700,2021-01-31 20:57:22.0110,3187,Warren St,40.721124,-74.038051,3483,Montgomery St,40.719420,-74.050990,44852,Subscriber,1958,1
11620,147,2021-01-31 21:05:05.2090,2021-01-31 21:07:32.8660,3186,Grove St PATH,40.719586,-74.043117,3187,Warren St,40.721124,-74.038051,46538,Subscriber,1972,1
11621,660,2021-01-31 21:06:23.5880,2021-01-31 21:17:23.8420,3211,Newark Ave,40.721525,-74.046305,3276,Marin Light Rail,40.714584,-74.042817,44398,Subscriber,1987,2
11622,384,2021-01-31 21:16:37.8220,2021-01-31 21:23:02.1240,3205,JC Medical Center,40.716540,-74.049638,3268,Lafayette Park,40.713464,-74.062859,41400,Subscriber,1989,1
11623,356,2021-01-31 23:24:50.8810,2021-01-31 23:30:47.3030,3639,Harborside,40.719252,-74.034234,3186,Grove St PATH,40.719586,-74.043117,43766,Subscriber,1994,1

In [370]:
# Clean column names

jan_df.columns = jan_df.columns.str.replace(' ', '_')
jan_df

,tripduration,starttime,stoptime,start_station_id,start_station_name,start_station_latitude,start_station_longitude,end_station_id,end_station_name,end_station_latitude,end_station_longitude,bikeid,usertype,birth_year,gender
0,266,2021-01-01 00:03:35.5100,2021-01-01 00:08:01.7770,3273,Manila & 1st,40.721651,-74.042884,3209,Brunswick St,40.724176,-74.050656,42494,Subscriber,1988,1
1,1543,2021-01-01 00:23:32.9250,2021-01-01 00:49:16.0830,3681,Grand St,40.715178,-74.037683,3213,Van Vorst Park,40.718489,-74.047727,45343,Customer,1996,2
2,1461,2021-01-01 00:23:50.7940,2021-01-01 00:48:12.5660,3681,Grand St,40.715178,-74.037683,3213,Van Vorst Park,40.718489,-74.047727,31794,Customer,1995,1
3,793,2021-01-01 00:31:09.0770,2021-01-01 00:44:22.9430,3185,City Hall,40.717732,-74.043845,3199,Newport Pkwy,40.728745,-74.032108,42316,Customer,1969,0
4,596,2021-01-01 00:35:52.1900,2021-01-01 00:45:48.7740,3639,Harborside,40.719252,-74.034234,3209,Brunswick St,40.724176,-74.050656,32575,Customer,1969,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11619,2476,2021-01-31 20:16:05.4700,2021-01-31 20:57:22.0110,3187,Warren St,40.721124,-74.038051,3483,Montgomery St,40.719420,-74.050990,44852,Subscriber,1958,1
11620,147,2021-01-31 21:05:05.2090,2021-01-31 21:07:32.8660,3186,Grove St PATH,40.719586,-74.043117,3187,Warren St,40.721124,-74.038051,46538,Subscriber,1972,1
11621,660,2021-01-31 21:06:23.5880,2021-01-31 21:17:23.8420,3211,Newark Ave,40.721525,-74.046305,3276,Marin Light Rail,40.714584,-74.042817,44398,Subscriber,1987,2
11622,384,2021-01-31 21:16:37.8220,2021-01-31 21:23:02.1240,3205,JC Medical Center,40.716540,-74.049638,3268,Lafayette Park,40.713464,-74.062859,41400,Subscriber,1989,1
11623,356,2021-01-31 23:24:50.8810,2021-01-31 23:30:47.3030,3639,Harborside,40.719252,-74.034234,3186,Grove St PATH,40.719586,-74.043117,43766,Subscriber,1994,1

In [371]:
# Bring in start station IDs

new_jan_df = pd.merge(jan_df, feb_df_station, on='start_station_name')
new_jan_df

,tripduration,starttime,stoptime,start_station_id_x,start_station_name,start_station_latitude,start_station_longitude,end_station_id,end_station_name,end_station_latitude,end_station_longitude,bikeid,usertype,birth_year,gender,start_station_id_y
0,266,2021-01-01 00:03:35.5100,2021-01-01 00:08:01.7770,3273,Manila & 1st,40.721651,-74.042884,3209,Brunswick St,40.724176,-74.050656,42494,Subscriber,1988,1,JC082
1,1710,2021-01-01 14:47:19.7140,2021-01-01 15:15:50.6870,3273,Manila & 1st,40.721651,-74.042884,3185,City Hall,40.717732,-74.043845,42422,Subscriber,1969,1,JC082
2,374,2021-01-02 09:18:47.6460,2021-01-02 09:25:02.0330,3273,Manila & 1st,40.721651,-74.042884,3270,Jersey & 6th St,40.725289,-74.045572,40464,Subscriber,1987,1,JC082
3,239,2021-01-02 10:05:45.8090,2021-01-02 10:09:45.3650,3273,Manila & 1st,40.721651,-74.042884,3203,Hamilton Park,40.727596,-74.044247,42368,Subscriber,1981,1,JC082
4,250,2021-01-02 11:45:06.8420,2021-01-02 11:49:17.1970,3273,Manila & 1st,40.721651,-74.042884,3638,Washington St,40.724294,-74.035483,45364,Subscriber,1988,2,JC082
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11619,2322,2021-01-28 12:47:43.6810,2021-01-28 13:26:26.0380,3196,Riverview Park,40.744319,-74.043991,3195,Sip Ave,40.730897,-74.063913,43361,Subscriber,1998,2,JC057
11620,1285,2021-01-28 14:44:09.1600,2021-01-28 15:05:34.3550,3196,Riverview Park,40.744319,-74.043991,3273,Manila & 1st,40.721651,-74.042884,44376,Subscriber,1968,1,JC057
11621,549,2021-01-29 19:42:20.8910,2021-01-29 19:51:29.9640,3196,Riverview Park,40.744319,-74.043991,3196,Riverview Park,40.744319,-74.043991,40954,Subscriber,1998,2,JC057
11622,562,2021-01-30 12:00:28.5500,2021-01-30 12:09:51.3200,3196,Riverview Park,40.744319,-74.043991,3269,Brunswick & 6th,40.726012,-74.050389,40954,Customer,1996,1,JC057
11623,990,2021-01-30 16:08:19.5370,2021-01-30 16:24:50.3170,3196,Riverview Park,40.744319,-74.043991,3187,Warren St,40.721124,-74.038051,39329,Subscriber,1988,1,JC057

In [372]:
# Bring in end station IDs

new_jan_df = pd.merge(new_jan_df, feb_df_station_end, on='end_station_name')
new_jan_df

,tripduration,starttime,stoptime,start_station_id_x,start_station_name,start_station_latitude,start_station_longitude,end_station_id_x,end_station_name,end_station_latitude,end_station_longitude,bikeid,usertype,birth_year,gender,start_station_id_y,end_station_id_y
0,266,2021-01-01 00:03:35.5100,2021-01-01 00:08:01.7770,3273,Manila & 1st,40.721651,-74.042884,3209,Brunswick St,40.724176,-74.050656,42494,Subscriber,1988,1,JC082,JC023
1,296,2021-01-02 23:16:11.3820,2021-01-02 23:21:08.3150,3273,Manila & 1st,40.721651,-74.042884,3209,Brunswick St,40.724176,-74.050656,42419,Subscriber,1988,1,JC082,JC023
2,269,2021-01-04 13:16:00.9080,2021-01-04 13:20:30.7690,3273,Manila & 1st,40.721651,-74.042884,3209,Brunswick St,40.724176,-74.050656,38460,Subscriber,1982,1,JC082,JC023
3,207,2021-01-05 22:53:03.5880,2021-01-05 22:56:30.7910,3273,Manila & 1st,40.721651,-74.042884,3209,Brunswick St,40.724176,-74.050656,47258,Subscriber,1988,1,JC082,JC023
4,238,2021-01-08 23:10:38.3990,2021-01-08 23:14:36.4990,3273,Manila & 1st,40.721651,-74.042884,3209,Brunswick St,40.724176,-74.050656,47257,Subscriber,1988,1,JC082,JC023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11612,104,2021-01-12 07:24:12.2750,2021-01-12 07:25:56.3690,3201,Dey St,40.737711,-74.066921,3201,Dey St,40.737711,-74.066921,28364,Subscriber,1966,1,JC065,JC065
11613,195,2021-01-10 15:25:53.3320,2021-01-10 15:29:09.3190,3220,5 Corners Library,40.734961,-74.059503,3201,Dey St,40.737711,-74.066921,28364,Subscriber,1961,1,JC018,JC065
11614,369,2021-01-12 22:09:16.7860,2021-01-12 22:15:25.9820,3220,5 Corners Library,40.734961,-74.059503,3201,Dey St,40.737711,-74.066921,46395,Subscriber,1998,1,JC018,JC065
11615,341,2021-01-12 22:09:52.5970,2021-01-12 22:15:34.1270,3220,5 Corners Library,40.734961,-74.059503,3201,Dey St,40.737711,-74.066921,41547,Customer,1969,0,JC018,JC065
11616,820,2021-01-19 14:11:14.0330,2021-01-19 14:24:54.8420,3196,Riverview Park,40.744319,-74.043991,3201,Dey St,40.737711,-74.066921,44698,Customer,1969,0,JC057,JC065

In [373]:
# Drop unnecessary columns

new_jan_df.drop(columns=['start_station_id_x', 'end_station_id_x'], inplace=True)
new_jan_df

,tripduration,starttime,stoptime,start_station_name,start_station_latitude,start_station_longitude,end_station_name,end_station_latitude,end_station_longitude,bikeid,usertype,birth_year,gender,start_station_id_y,end_station_id_y
0,266,2021-01-01 00:03:35.5100,2021-01-01 00:08:01.7770,Manila & 1st,40.721651,-74.042884,Brunswick St,40.724176,-74.050656,42494,Subscriber,1988,1,JC082,JC023
1,296,2021-01-02 23:16:11.3820,2021-01-02 23:21:08.3150,Manila & 1st,40.721651,-74.042884,Brunswick St,40.724176,-74.050656,42419,Subscriber,1988,1,JC082,JC023
2,269,2021-01-04 13:16:00.9080,2021-01-04 13:20:30.7690,Manila & 1st,40.721651,-74.042884,Brunswick St,40.724176,-74.050656,38460,Subscriber,1982,1,JC082,JC023
3,207,2021-01-05 22:53:03.5880,2021-01-05 22:56:30.7910,Manila & 1st,40.721651,-74.042884,Brunswick St,40.724176,-74.050656,47258,Subscriber,1988,1,JC082,JC023
4,238,2021-01-08 23:10:38.3990,2021-01-08 23:14:36.4990,Manila & 1st,40.721651,-74.042884,Brunswick St,40.724176,-74.050656,47257,Subscriber,1988,1,JC082,JC023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11612,104,2021-01-12 07:24:12.2750,2021-01-12 07:25:56.3690,Dey St,40.737711,-74.066921,Dey St,40.737711,-74.066921,28364,Subscriber,1966,1,JC065,JC065
11613,195,2021-01-10 15:25:53.3320,2021-01-10 15:29:09.3190,5 Corners Library,40.734961,-74.059503,Dey St,40.737711,-74.066921,28364,Subscriber,1961,1,JC018,JC065
11614,369,2021-01-12 22:09:16.7860,2021-01-12 22:15:25.9820,5 Corners Library,40.734961,-74.059503,Dey St,40.737711,-74.066921,46395,Subscriber,1998,1,JC018,JC065
11615,341,2021-01-12 22:09:52.5970,2021-01-12 22:15:34.1270,5 Corners Library,40.734961,-74.059503,Dey St,40.737711,-74.066921,41547,Customer,1969,0,JC018,JC065
11616,820,2021-01-19 14:11:14.0330,2021-01-19 14:24:54.8420,Riverview Park,40.744319,-74.043991,Dey St,40.737711,-74.066921,44698,Customer,1969,0,JC057,JC065

In [374]:
# Rename columns

new_jan_df.rename(columns = {'start_station_id_y':'start_station_id', 'end_station_id_y':'end_station_id'}, inplace=True)
new_jan_df

,tripduration,starttime,stoptime,start_station_name,start_station_latitude,start_station_longitude,end_station_name,end_station_latitude,end_station_longitude,bikeid,usertype,birth_year,gender,start_station_id,end_station_id
0,266,2021-01-01 00:03:35.5100,2021-01-01 00:08:01.7770,Manila & 1st,40.721651,-74.042884,Brunswick St,40.724176,-74.050656,42494,Subscriber,1988,1,JC082,JC023
1,296,2021-01-02 23:16:11.3820,2021-01-02 23:21:08.3150,Manila & 1st,40.721651,-74.042884,Brunswick St,40.724176,-74.050656,42419,Subscriber,1988,1,JC082,JC023
2,269,2021-01-04 13:16:00.9080,2021-01-04 13:20:30.7690,Manila & 1st,40.721651,-74.042884,Brunswick St,40.724176,-74.050656,38460,Subscriber,1982,1,JC082,JC023
3,207,2021-01-05 22:53:03.5880,2021-01-05 22:56:30.7910,Manila & 1st,40.721651,-74.042884,Brunswick St,40.724176,-74.050656,47258,Subscriber,1988,1,JC082,JC023
4,238,2021-01-08 23:10:38.3990,2021-01-08 23:14:36.4990,Manila & 1st,40.721651,-74.042884,Brunswick St,40.724176,-74.050656,47257,Subscriber,1988,1,JC082,JC023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11612,104,2021-01-12 07:24:12.2750,2021-01-12 07:25:56.3690,Dey St,40.737711,-74.066921,Dey St,40.737711,-74.066921,28364,Subscriber,1966,1,JC065,JC065
11613,195,2021-01-10 15:25:53.3320,2021-01-10 15:29:09.3190,5 Corners Library,40.734961,-74.059503,Dey St,40.737711,-74.066921,28364,Subscriber,1961,1,JC018,JC065
11614,369,2021-01-12 22:09:16.7860,2021-01-12 22:15:25.9820,5 Corners Library,40.734961,-74.059503,Dey St,40.737711,-74.066921,46395,Subscriber,1998,1,JC018,JC065
11615,341,2021-01-12 22:09:52.5970,2021-01-12 22:15:34.1270,5 Corners Library,40.734961,-74.059503,Dey St,40.737711,-74.066921,41547,Customer,1969,0,JC018,JC065
11616,820,2021-01-19 14:11:14.0330,2021-01-19 14:24:54.8420,Riverview Park,40.744319,-74.043991,Dey St,40.737711,-74.066921,44698,Customer,1969,0,JC057,JC065

In [375]:
# Reorder columns, push to csv

new_jan_df = new_jan_df.reindex(columns=['tripduration', 'starttime', 'stoptime', 'start_station_id', 'start_station_name', 'start_station_latitude', 'start_station_longitude', 'end_station_id', 'end_station_name', 'end_station_latitude', 'end_station_longitude', 'bikeid', 'usertype', 'birth_year', 'gender'])
new_jan_df.to_csv(r'/Users/amber/Desktop/GitHub/Tableau-DataClean/csvs/JC-202101-citibike-tripdata-CLEANED.csv', index=False)
new_jan_df

,tripduration,starttime,stoptime,start_station_id,start_station_name,start_station_latitude,start_station_longitude,end_station_id,end_station_name,end_station_latitude,end_station_longitude,bikeid,usertype,birth_year,gender
0,266,2021-01-01 00:03:35.5100,2021-01-01 00:08:01.7770,JC082,Manila & 1st,40.721651,-74.042884,JC023,Brunswick St,40.724176,-74.050656,42494,Subscriber,1988,1
1,296,2021-01-02 23:16:11.3820,2021-01-02 23:21:08.3150,JC082,Manila & 1st,40.721651,-74.042884,JC023,Brunswick St,40.724176,-74.050656,42419,Subscriber,1988,1
2,269,2021-01-04 13:16:00.9080,2021-01-04 13:20:30.7690,JC082,Manila & 1st,40.721651,-74.042884,JC023,Brunswick St,40.724176,-74.050656,38460,Subscriber,1982,1
3,207,2021-01-05 22:53:03.5880,2021-01-05 22:56:30.7910,JC082,Manila & 1st,40.721651,-74.042884,JC023,Brunswick St,40.724176,-74.050656,47258,Subscriber,1988,1
4,238,2021-01-08 23:10:38.3990,2021-01-08 23:14:36.4990,JC082,Manila & 1st,40.721651,-74.042884,JC023,Brunswick St,40.724176,-74.050656,47257,Subscriber,1988,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11612,104,2021-01-12 07:24:12.2750,2021-01-12 07:25:56.3690,JC065,Dey St,40.737711,-74.066921,JC065,Dey St,40.737711,-74.066921,28364,Subscriber,1966,1
11613,195,2021-01-10 15:25:53.3320,2021-01-10 15:29:09.3190,JC018,5 Corners Library,40.734961,-74.059503,JC065,Dey St,40.737711,-74.066921,28364,Subscriber,1961,1
11614,369,2021-01-12 22:09:16.7860,2021-01-12 22:15:25.9820,JC018,5 Corners Library,40.734961,-74.059503,JC065,Dey St,40.737711,-74.066921,46395,Subscriber,1998,1
11615,341,2021-01-12 22:09:52.5970,2021-01-12 22:15:34.1270,JC018,5 Corners Library,40.734961,-74.059503,JC065,Dey St,40.737711,-74.066921,41547,Customer,1969,0
11616,820,2021-01-19 14:11:14.0330,2021-01-19 14:24:54.8420,JC057,Riverview Park,40.744319,-74.043991,JC065,Dey St,40.737711,-74.066921,44698,Customer,1969,0

In [376]:
# Updating usertype to match Feb-Mar data -- making assumption that Subscriber = Member and Customer = Casual
new_jan_df['usertype'] = new_jan_df['usertype'].replace(['Subscriber','Customer'], ['member', 'casual'])
new_jan_df

,tripduration,starttime,stoptime,start_station_id,start_station_name,start_station_latitude,start_station_longitude,end_station_id,end_station_name,end_station_latitude,end_station_longitude,bikeid,usertype,birth_year,gender
0,266,2021-01-01 00:03:35.5100,2021-01-01 00:08:01.7770,JC082,Manila & 1st,40.721651,-74.042884,JC023,Brunswick St,40.724176,-74.050656,42494,member,1988,1
1,296,2021-01-02 23:16:11.3820,2021-01-02 23:21:08.3150,JC082,Manila & 1st,40.721651,-74.042884,JC023,Brunswick St,40.724176,-74.050656,42419,member,1988,1
2,269,2021-01-04 13:16:00.9080,2021-01-04 13:20:30.7690,JC082,Manila & 1st,40.721651,-74.042884,JC023,Brunswick St,40.724176,-74.050656,38460,member,1982,1
3,207,2021-01-05 22:53:03.5880,2021-01-05 22:56:30.7910,JC082,Manila & 1st,40.721651,-74.042884,JC023,Brunswick St,40.724176,-74.050656,47258,member,1988,1
4,238,2021-01-08 23:10:38.3990,2021-01-08 23:14:36.4990,JC082,Manila & 1st,40.721651,-74.042884,JC023,Brunswick St,40.724176,-74.050656,47257,member,1988,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11612,104,2021-01-12 07:24:12.2750,2021-01-12 07:25:56.3690,JC065,Dey St,40.737711,-74.066921,JC065,Dey St,40.737711,-74.066921,28364,member,1966,1
11613,195,2021-01-10 15:25:53.3320,2021-01-10 15:29:09.3190,JC018,5 Corners Library,40.734961,-74.059503,JC065,Dey St,40.737711,-74.066921,28364,member,1961,1
11614,369,2021-01-12 22:09:16.7860,2021-01-12 22:15:25.9820,JC018,5 Corners Library,40.734961,-74.059503,JC065,Dey St,40.737711,-74.066921,46395,member,1998,1
11615,341,2021-01-12 22:09:52.5970,2021-01-12 22:15:34.1270,JC018,5 Corners Library,40.734961,-74.059503,JC065,Dey St,40.737711,-74.066921,41547,casual,1969,0
11616,820,2021-01-19 14:11:14.0330,2021-01-19 14:24:54.8420,JC057,Riverview Park,40.744319,-74.043991,JC065,Dey St,40.737711,-74.066921,44698,casual,1969,0

In [377]:
# Renamed additional columns to match Feb-Mar data

new_jan_df.rename(columns={'starttime':'started_at', 'stoptime':'ended_at', 'start_station_latitude':'start_lat', 'start_station_longitude':'start_lng', 'end_station_latitude':'end_lat', 'end_station_longitude':'end_lng', 'usertype':'member_casual'}, inplace=True)
new_jan_df.to_csv(r'/Users/amber/Desktop/GitHub/Tableau-DataClean/csvs/JC-202101-citibike-tripdata-CLEANED.csv', index=False)
new_jan_df

,tripduration,started_at,ended_at,start_station_id,start_station_name,start_lat,start_lng,end_station_id,end_station_name,end_lat,end_lng,bikeid,member_casual,birth_year,gender
0,266,2021-01-01 00:03:35.5100,2021-01-01 00:08:01.7770,JC082,Manila & 1st,40.721651,-74.042884,JC023,Brunswick St,40.724176,-74.050656,42494,member,1988,1
1,296,2021-01-02 23:16:11.3820,2021-01-02 23:21:08.3150,JC082,Manila & 1st,40.721651,-74.042884,JC023,Brunswick St,40.724176,-74.050656,42419,member,1988,1
2,269,2021-01-04 13:16:00.9080,2021-01-04 13:20:30.7690,JC082,Manila & 1st,40.721651,-74.042884,JC023,Brunswick St,40.724176,-74.050656,38460,member,1982,1
3,207,2021-01-05 22:53:03.5880,2021-01-05 22:56:30.7910,JC082,Manila & 1st,40.721651,-74.042884,JC023,Brunswick St,40.724176,-74.050656,47258,member,1988,1
4,238,2021-01-08 23:10:38.3990,2021-01-08 23:14:36.4990,JC082,Manila & 1st,40.721651,-74.042884,JC023,Brunswick St,40.724176,-74.050656,47257,member,1988,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11612,104,2021-01-12 07:24:12.2750,2021-01-12 07:25:56.3690,JC065,Dey St,40.737711,-74.066921,JC065,Dey St,40.737711,-74.066921,28364,member,1966,1
11613,195,2021-01-10 15:25:53.3320,2021-01-10 15:29:09.3190,JC018,5 Corners Library,40.734961,-74.059503,JC065,Dey St,40.737711,-74.066921,28364,member,1961,1
11614,369,2021-01-12 22:09:16.7860,2021-01-12 22:15:25.9820,JC018,5 Corners Library,40.734961,-74.059503,JC065,Dey St,40.737711,-74.066921,46395,member,1998,1
11615,341,2021-01-12 22:09:52.5970,2021-01-12 22:15:34.1270,JC018,5 Corners Library,40.734961,-74.059503,JC065,Dey St,40.737711,-74.066921,41547,casual,1969,0
11616,820,2021-01-19 14:11:14.0330,2021-01-19 14:24:54.8420,JC057,Riverview Park,40.744319,-74.043991,JC065,Dey St,40.737711,-74.066921,44698,casual,1969,0

In [378]:
# Read in Mar data

mar_df = pd.read_csv("/Users/amber/Desktop/GitHub/Tableau-DataClean/csvs/JC-202103-citibike-tripdata.csv")
mar_df

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,ABBBB4D89C620898,docked_bike,2021-03-03 10:32:07,2021-03-03 10:32:40,Jackson Square,JC063,Jackson Square,JC063,40.711130,-74.078900,40.711130,-74.078900,member
1,987BC8C414C77F3E,docked_bike,2021-03-14 00:21:37,2021-03-14 00:22:59,Jackson Square,JC063,Jackson Square,JC063,40.711130,-74.078900,40.711130,-74.078900,casual
2,342C5C515F0F8BCB,docked_bike,2021-03-21 14:39:46,2021-03-21 15:33:10,Jackson Square,JC063,Warren St,JC006,40.711130,-74.078900,40.721124,-74.038051,casual
3,AB28945141163E31,docked_bike,2021-03-14 00:27:21,2021-03-14 00:31:07,Jackson Square,JC063,Jackson Square,JC063,40.711130,-74.078900,40.711130,-74.078900,casual
4,4F5758803BC3DE72,docked_bike,2021-03-12 20:45:29,2021-03-13 08:58:59,Jackson Square,JC063,Jackson Square,JC063,40.711130,-74.078900,40.711130,-74.078900,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
17118,6749C4D091AAA8CA,docked_bike,2021-03-29 19:30:20,2021-03-29 19:38:10,Harborside,JC104,Morris Canal,JC072,40.719251,-74.034234,40.712419,-74.038526,member
17119,3DBAB9D9FA2758A3,docked_bike,2021-03-12 18:49:06,2021-03-12 18:54:35,Harborside,JC104,Morris Canal,JC072,40.719251,-74.034234,40.712419,-74.038526,member
17120,E0183D5DD0C62E12,docked_bike,2021-03-28 12:29:15,2021-03-28 12:34:40,Harborside,JC104,Newark Ave,JC032,40.719251,-74.034234,40.721525,-74.046305,member
17121,D39E4D9D8F735AB8,docked_bike,2021-03-23 13:03:35,2021-03-23 13:10:25,Harborside,JC104,Newark Ave,JC032,40.719251,-74.034234,40.721525,-74.046305,member
17122,87D47774A82633A6,docked_bike,2021-03-24 10:12:54,2021-03-24 10:21:17,Harborside,JC104,Newark Ave,JC032,40.719251,-74.034234,40.721525,-74.046305,member

In [379]:
# Combine Feb and Mar data

feb_mar_df = pd.concat([feb_df, mar_df]).reset_index(drop=True)
feb_mar_df.to_csv(r'/Users/amber/Desktop/GitHub/Tableau-DataClean/csvs/FEB-MAR-citibike-tripdata.csv', index=False)
feb_mar_df

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,121DD7DD23CB1335,docked_bike,2021-02-03 23:11:28,2021-02-03 23:18:28,Hoboken Ave at Monmouth St,JC105,Christ Hospital,JC034,40.735208,-74.046964,40.734786,-74.050444,member
1,FD73FB85F008349D,docked_bike,2021-02-27 16:34:05,2021-02-27 16:56:40,Newport Pkwy,JC008,Marin Light Rail,JC013,40.728744,-74.032108,40.714584,-74.042817,member
2,39F9E6663CB5FDF6,docked_bike,2021-02-26 23:16:04,2021-02-26 23:22:25,Journal Square,JC103,Baldwin at Montgomery,JC020,40.733670,-74.062500,40.723659,-74.064194,member
3,A64745CB0792EC6F,docked_bike,2021-02-24 16:51:50,2021-02-24 17:16:09,Hoboken Ave at Monmouth St,JC105,Hoboken Ave at Monmouth St,JC105,40.735208,-74.046963,40.735208,-74.046964,casual
4,75CC76EB9543764A,docked_bike,2021-02-24 20:44:16,2021-02-24 20:44:46,Hoboken Ave at Monmouth St,JC105,Hoboken Ave at Monmouth St,JC105,40.735208,-74.046963,40.735208,-74.046964,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
21999,6749C4D091AAA8CA,docked_bike,2021-03-29 19:30:20,2021-03-29 19:38:10,Harborside,JC104,Morris Canal,JC072,40.719251,-74.034234,40.712419,-74.038526,member
22000,3DBAB9D9FA2758A3,docked_bike,2021-03-12 18:49:06,2021-03-12 18:54:35,Harborside,JC104,Morris Canal,JC072,40.719251,-74.034234,40.712419,-74.038526,member
22001,E0183D5DD0C62E12,docked_bike,2021-03-28 12:29:15,2021-03-28 12:34:40,Harborside,JC104,Newark Ave,JC032,40.719251,-74.034234,40.721525,-74.046305,member
22002,D39E4D9D8F735AB8,docked_bike,2021-03-23 13:03:35,2021-03-23 13:10:25,Harborside,JC104,Newark Ave,JC032,40.719251,-74.034234,40.721525,-74.046305,member
22003,87D47774A82633A6,docked_bike,2021-03-24 10:12:54,2021-03-24 10:21:17,Harborside,JC104,Newark Ave,JC032,40.719251,-74.034234,40.721525,-74.046305,member

In [380]:
# Combine Jan and Feb-Mar data for 3-Month span

jan_mar_df = pd.concat([new_jan_df, feb_mar_df]).reset_index(drop=True)
jan_mar_df

,tripduration,started_at,ended_at,start_station_id,start_station_name,start_lat,start_lng,end_station_id,end_station_name,end_lat,end_lng,bikeid,member_casual,birth_year,gender,ride_id,rideable_type
0,266.0,2021-01-01 00:03:35.5100,2021-01-01 00:08:01.7770,JC082,Manila & 1st,40.721651,-74.042884,JC023,Brunswick St,40.724176,-74.050656,42494.0,member,1988.0,1.0,NaN,NaN
1,296.0,2021-01-02 23:16:11.3820,2021-01-02 23:21:08.3150,JC082,Manila & 1st,40.721651,-74.042884,JC023,Brunswick St,40.724176,-74.050656,42419.0,member,1988.0,1.0,NaN,NaN
2,269.0,2021-01-04 13:16:00.9080,2021-01-04 13:20:30.7690,JC082,Manila & 1st,40.721651,-74.042884,JC023,Brunswick St,40.724176,-74.050656,38460.0,member,1982.0,1.0,NaN,NaN
3,207.0,2021-01-05 22:53:03.5880,2021-01-05 22:56:30.7910,JC082,Manila & 1st,40.721651,-74.042884,JC023,Brunswick St,40.724176,-74.050656,47258.0,member,1988.0,1.0,NaN,NaN
4,238.0,2021-01-08 23:10:38.3990,2021-01-08 23:14:36.4990,JC082,Manila & 1st,40.721651,-74.042884,JC023,Brunswick St,40.724176,-74.050656,47257.0,member,1988.0,1.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33616,NaN,2021-03-29 19:30:20,2021-03-29 19:38:10,JC104,Harborside,40.719251,-74.034234,JC072,Morris Canal,40.712419,-74.038526,NaN,member,NaN,NaN,6749C4D091AAA8CA,docked_bike
33617,NaN,2021-03-12 18:49:06,2021-03-12 18:54:35,JC104,Harborside,40.719251,-74.034234,JC072,Morris Canal,40.712419,-74.038526,NaN,member,NaN,NaN,3DBAB9D9FA2758A3,docked_bike
33618,NaN,2021-03-28 12:29:15,2021-03-28 12:34:40,JC104,Harborside,40.719251,-74.034234,JC032,Newark Ave,40.721525,-74.046305,NaN,member,NaN,NaN,E0183D5DD0C62E12,docked_bike
33619,NaN,2021-03-23 13:03:35,2021-03-23 13:10:25,JC104,Harborside,40.719251,-74.034234,JC032,Newark Ave,40.721525,-74.046305,NaN,member,NaN,NaN,D39E4D9D8F735AB8,docked_bike
33620,NaN,2021-03-24 10:12:54,2021-03-24 10:21:17,JC104,Harborside,40.719251,-74.034234,JC032,Newark Ave,40.721525,-74.046305,NaN,member,NaN,NaN,87D47774A82633A6,docked_bike

In [381]:
# Drop columns that won't be used - not used across months

jan_mar_df.drop(['tripduration', 'bikeid', 'birth_year', 'gender', 'ride_id', 'rideable_type'], axis=1, inplace=True)
jan_mar_df

,started_at,ended_at,start_station_id,start_station_name,start_lat,start_lng,end_station_id,end_station_name,end_lat,end_lng,member_casual
0,2021-01-01 00:03:35.5100,2021-01-01 00:08:01.7770,JC082,Manila & 1st,40.721651,-74.042884,JC023,Brunswick St,40.724176,-74.050656,member
1,2021-01-02 23:16:11.3820,2021-01-02 23:21:08.3150,JC082,Manila & 1st,40.721651,-74.042884,JC023,Brunswick St,40.724176,-74.050656,member
2,2021-01-04 13:16:00.9080,2021-01-04 13:20:30.7690,JC082,Manila & 1st,40.721651,-74.042884,JC023,Brunswick St,40.724176,-74.050656,member
3,2021-01-05 22:53:03.5880,2021-01-05 22:56:30.7910,JC082,Manila & 1st,40.721651,-74.042884,JC023,Brunswick St,40.724176,-74.050656,member
4,2021-01-08 23:10:38.3990,2021-01-08 23:14:36.4990,JC082,Manila & 1st,40.721651,-74.042884,JC023,Brunswick St,40.724176,-74.050656,member
...,...,...,...,...,...,...,...,...,...,...,...
33616,2021-03-29 19:30:20,2021-03-29 19:38:10,JC104,Harborside,40.719251,-74.034234,JC072,Morris Canal,40.712419,-74.038526,member
33617,2021-03-12 18:49:06,2021-03-12 18:54:35,JC104,Harborside,40.719251,-74.034234,JC072,Morris Canal,40.712419,-74.038526,member
33618,2021-03-28 12:29:15,2021-03-28 12:34:40,JC104,Harborside,40.719251,-74.034234,JC032,Newark Ave,40.721525,-74.046305,member
33619,2021-03-23 13:03:35,2021-03-23 13:10:25,JC104,Harborside,40.719251,-74.034234,JC032,Newark Ave,40.721525,-74.046305,member
33620,2021-03-24 10:12:54,2021-03-24 10:21:17,JC104,Harborside,40.719251,-74.034234,JC032,Newark Ave,40.721525,-74.046305,member

In [382]:
# Clean up Station Names to use

jan_mar_df = jan_mar_df.replace('\&','and',regex=True)
jan_mar_df

,started_at,ended_at,start_station_id,start_station_name,start_lat,start_lng,end_station_id,end_station_name,end_lat,end_lng,member_casual
0,2021-01-01 00:03:35.5100,2021-01-01 00:08:01.7770,JC082,Manila and 1st,40.721651,-74.042884,JC023,Brunswick St,40.724176,-74.050656,member
1,2021-01-02 23:16:11.3820,2021-01-02 23:21:08.3150,JC082,Manila and 1st,40.721651,-74.042884,JC023,Brunswick St,40.724176,-74.050656,member
2,2021-01-04 13:16:00.9080,2021-01-04 13:20:30.7690,JC082,Manila and 1st,40.721651,-74.042884,JC023,Brunswick St,40.724176,-74.050656,member
3,2021-01-05 22:53:03.5880,2021-01-05 22:56:30.7910,JC082,Manila and 1st,40.721651,-74.042884,JC023,Brunswick St,40.724176,-74.050656,member
4,2021-01-08 23:10:38.3990,2021-01-08 23:14:36.4990,JC082,Manila and 1st,40.721651,-74.042884,JC023,Brunswick St,40.724176,-74.050656,member
...,...,...,...,...,...,...,...,...,...,...,...
33616,2021-03-29 19:30:20,2021-03-29 19:38:10,JC104,Harborside,40.719251,-74.034234,JC072,Morris Canal,40.712419,-74.038526,member
33617,2021-03-12 18:49:06,2021-03-12 18:54:35,JC104,Harborside,40.719251,-74.034234,JC072,Morris Canal,40.712419,-74.038526,member
33618,2021-03-28 12:29:15,2021-03-28 12:34:40,JC104,Harborside,40.719251,-74.034234,JC032,Newark Ave,40.721525,-74.046305,member
33619,2021-03-23 13:03:35,2021-03-23 13:10:25,JC104,Harborside,40.719251,-74.034234,JC032,Newark Ave,40.721525,-74.046305,member
33620,2021-03-24 10:12:54,2021-03-24 10:21:17,JC104,Harborside,40.719251,-74.034234,JC032,Newark Ave,40.721525,-74.046305,member

In [383]:
jan_mar_df['start_station_name'] = jan_mar_df['start_station_name'].str.replace(" ","-")
jan_mar_df['end_station_name'] = jan_mar_df['end_station_name'].str.replace(" ","-")
jan_mar_df

,started_at,ended_at,start_station_id,start_station_name,start_lat,start_lng,end_station_id,end_station_name,end_lat,end_lng,member_casual
0,2021-01-01 00:03:35.5100,2021-01-01 00:08:01.7770,JC082,Manila-and-1st,40.721651,-74.042884,JC023,Brunswick-St,40.724176,-74.050656,member
1,2021-01-02 23:16:11.3820,2021-01-02 23:21:08.3150,JC082,Manila-and-1st,40.721651,-74.042884,JC023,Brunswick-St,40.724176,-74.050656,member
2,2021-01-04 13:16:00.9080,2021-01-04 13:20:30.7690,JC082,Manila-and-1st,40.721651,-74.042884,JC023,Brunswick-St,40.724176,-74.050656,member
3,2021-01-05 22:53:03.5880,2021-01-05 22:56:30.7910,JC082,Manila-and-1st,40.721651,-74.042884,JC023,Brunswick-St,40.724176,-74.050656,member
4,2021-01-08 23:10:38.3990,2021-01-08 23:14:36.4990,JC082,Manila-and-1st,40.721651,-74.042884,JC023,Brunswick-St,40.724176,-74.050656,member
...,...,...,...,...,...,...,...,...,...,...,...
33616,2021-03-29 19:30:20,2021-03-29 19:38:10,JC104,Harborside,40.719251,-74.034234,JC072,Morris-Canal,40.712419,-74.038526,member
33617,2021-03-12 18:49:06,2021-03-12 18:54:35,JC104,Harborside,40.719251,-74.034234,JC072,Morris-Canal,40.712419,-74.038526,member
33618,2021-03-28 12:29:15,2021-03-28 12:34:40,JC104,Harborside,40.719251,-74.034234,JC032,Newark-Ave,40.721525,-74.046305,member
33619,2021-03-23 13:03:35,2021-03-23 13:10:25,JC104,Harborside,40.719251,-74.034234,JC032,Newark-Ave,40.721525,-74.046305,member
33620,2021-03-24 10:12:54,2021-03-24 10:21:17,JC104,Harborside,40.719251,-74.034234,JC032,Newark-Ave,40.721525,-74.046305,member

In [384]:
# create path_id field for future spider map
jan_mar_df['path_id'] = jan_mar_df['start_station_name'] + '_' + jan_mar_df['end_station_name']
jan_mar_df['path_id_2'] = jan_mar_df['start_station_id'] + '_' + jan_mar_df['end_station_id']
jan_mar_df

,started_at,ended_at,start_station_id,start_station_name,start_lat,start_lng,end_station_id,end_station_name,end_lat,end_lng,member_casual,path_id,path_id_2
0,2021-01-01 00:03:35.5100,2021-01-01 00:08:01.7770,JC082,Manila-and-1st,40.721651,-74.042884,JC023,Brunswick-St,40.724176,-74.050656,member,Manila-and-1st_Brunswick-St,JC082_JC023
1,2021-01-02 23:16:11.3820,2021-01-02 23:21:08.3150,JC082,Manila-and-1st,40.721651,-74.042884,JC023,Brunswick-St,40.724176,-74.050656,member,Manila-and-1st_Brunswick-St,JC082_JC023
2,2021-01-04 13:16:00.9080,2021-01-04 13:20:30.7690,JC082,Manila-and-1st,40.721651,-74.042884,JC023,Brunswick-St,40.724176,-74.050656,member,Manila-and-1st_Brunswick-St,JC082_JC023
3,2021-01-05 22:53:03.5880,2021-01-05 22:56:30.7910,JC082,Manila-and-1st,40.721651,-74.042884,JC023,Brunswick-St,40.724176,-74.050656,member,Manila-and-1st_Brunswick-St,JC082_JC023
4,2021-01-08 23:10:38.3990,2021-01-08 23:14:36.4990,JC082,Manila-and-1st,40.721651,-74.042884,JC023,Brunswick-St,40.724176,-74.050656,member,Manila-and-1st_Brunswick-St,JC082_JC023
...,...,...,...,...,...,...,...,...,...,...,...,...,...
33616,2021-03-29 19:30:20,2021-03-29 19:38:10,JC104,Harborside,40.719251,-74.034234,JC072,Morris-Canal,40.712419,-74.038526,member,Harborside_Morris-Canal,JC104_JC072
33617,2021-03-12 18:49:06,2021-03-12 18:54:35,JC104,Harborside,40.719251,-74.034234,JC072,Morris-Canal,40.712419,-74.038526,member,Harborside_Morris-Canal,JC104_JC072
33618,2021-03-28 12:29:15,2021-03-28 12:34:40,JC104,Harborside,40.719251,-74.034234,JC032,Newark-Ave,40.721525,-74.046305,member,Harborside_Newark-Ave,JC104_JC032
33619,2021-03-23 13:03:35,2021-03-23 13:10:25,JC104,Harborside,40.719251,-74.034234,JC032,Newark-Ave,40.721525,-74.046305,member,Harborside_Newark-Ave,JC104_JC032
33620,2021-03-24 10:12:54,2021-03-24 10:21:17,JC104,Harborside,40.719251,-74.034234,JC032,Newark-Ave,40.721525,-74.046305,member,Harborside_Newark-Ave,JC104_JC032

In [389]:
# standardize lat and lon coordinates - was getting layered values in Tableau visualization due to slight variations in lat/lng
jan_mar_df = jan_mar_df.round(3)
jan_mar_df.to_csv(r'/Users/amber/Desktop/GitHub/Tableau-DataClean/csvs/JAN-MAR-citibike-tripdata.csv', index=False)

In [391]:
# split dataframes to create origin-destination rows to create dataset for spider map
origin_df = jan_mar_df[[
'started_at', 'ended_at', 'start_station_name', 'start_station_id', 'start_lat', 'start_lng', 'member_casual', 'path_id', 'path_id_2']].copy()
origin_df

,started_at,ended_at,start_station_name,start_station_id,start_lat,start_lng,member_casual,path_id,path_id_2
0,2021-01-01 00:03:35.5100,2021-01-01 00:08:01.7770,Manila-and-1st,JC082,40.722,-74.043,member,Manila-and-1st_Brunswick-St,JC082_JC023
1,2021-01-02 23:16:11.3820,2021-01-02 23:21:08.3150,Manila-and-1st,JC082,40.722,-74.043,member,Manila-and-1st_Brunswick-St,JC082_JC023
2,2021-01-04 13:16:00.9080,2021-01-04 13:20:30.7690,Manila-and-1st,JC082,40.722,-74.043,member,Manila-and-1st_Brunswick-St,JC082_JC023
3,2021-01-05 22:53:03.5880,2021-01-05 22:56:30.7910,Manila-and-1st,JC082,40.722,-74.043,member,Manila-and-1st_Brunswick-St,JC082_JC023
4,2021-01-08 23:10:38.3990,2021-01-08 23:14:36.4990,Manila-and-1st,JC082,40.722,-74.043,member,Manila-and-1st_Brunswick-St,JC082_JC023
...,...,...,...,...,...,...,...,...,...
33616,2021-03-29 19:30:20,2021-03-29 19:38:10,Harborside,JC104,40.719,-74.034,member,Harborside_Morris-Canal,JC104_JC072
33617,2021-03-12 18:49:06,2021-03-12 18:54:35,Harborside,JC104,40.719,-74.034,member,Harborside_Morris-Canal,JC104_JC072
33618,2021-03-28 12:29:15,2021-03-28 12:34:40,Harborside,JC104,40.719,-74.034,member,Harborside_Newark-Ave,JC104_JC032
33619,2021-03-23 13:03:35,2021-03-23 13:10:25,Harborside,JC104,40.719,-74.034,member,Harborside_Newark-Ave,JC104_JC032
33620,2021-03-24 10:12:54,2021-03-24 10:21:17,Harborside,JC104,40.719,-74.034,member,Harborside_Newark-Ave,JC104_JC032

In [392]:
destination_df = jan_mar_df[[
'started_at', 'ended_at', 'end_station_name', 'end_station_id', 'end_lat', 'end_lng', 'member_casual', 'path_id', 'path_id_2']].copy()
destination_df

,started_at,ended_at,end_station_name,end_station_id,end_lat,end_lng,member_casual,path_id,path_id_2
0,2021-01-01 00:03:35.5100,2021-01-01 00:08:01.7770,Brunswick-St,JC023,40.724,-74.051,member,Manila-and-1st_Brunswick-St,JC082_JC023
1,2021-01-02 23:16:11.3820,2021-01-02 23:21:08.3150,Brunswick-St,JC023,40.724,-74.051,member,Manila-and-1st_Brunswick-St,JC082_JC023
2,2021-01-04 13:16:00.9080,2021-01-04 13:20:30.7690,Brunswick-St,JC023,40.724,-74.051,member,Manila-and-1st_Brunswick-St,JC082_JC023
3,2021-01-05 22:53:03.5880,2021-01-05 22:56:30.7910,Brunswick-St,JC023,40.724,-74.051,member,Manila-and-1st_Brunswick-St,JC082_JC023
4,2021-01-08 23:10:38.3990,2021-01-08 23:14:36.4990,Brunswick-St,JC023,40.724,-74.051,member,Manila-and-1st_Brunswick-St,JC082_JC023
...,...,...,...,...,...,...,...,...,...
33616,2021-03-29 19:30:20,2021-03-29 19:38:10,Morris-Canal,JC072,40.712,-74.039,member,Harborside_Morris-Canal,JC104_JC072
33617,2021-03-12 18:49:06,2021-03-12 18:54:35,Morris-Canal,JC072,40.712,-74.039,member,Harborside_Morris-Canal,JC104_JC072
33618,2021-03-28 12:29:15,2021-03-28 12:34:40,Newark-Ave,JC032,40.722,-74.046,member,Harborside_Newark-Ave,JC104_JC032
33619,2021-03-23 13:03:35,2021-03-23 13:10:25,Newark-Ave,JC032,40.722,-74.046,member,Harborside_Newark-Ave,JC104_JC032
33620,2021-03-24 10:12:54,2021-03-24 10:21:17,Newark-Ave,JC032,40.722,-74.046,member,Harborside_Newark-Ave,JC104_JC032

In [393]:
origin_df['origin_destination'] = 'origin'
destination_df['origin_destination'] = 'destination'

In [395]:
# origin_df
destination_df

,started_at,ended_at,end_station_name,end_station_id,end_lat,end_lng,member_casual,path_id,path_id_2,origin_destination
0,2021-01-01 00:03:35.5100,2021-01-01 00:08:01.7770,Brunswick-St,JC023,40.724,-74.051,member,Manila-and-1st_Brunswick-St,JC082_JC023,destination
1,2021-01-02 23:16:11.3820,2021-01-02 23:21:08.3150,Brunswick-St,JC023,40.724,-74.051,member,Manila-and-1st_Brunswick-St,JC082_JC023,destination
2,2021-01-04 13:16:00.9080,2021-01-04 13:20:30.7690,Brunswick-St,JC023,40.724,-74.051,member,Manila-and-1st_Brunswick-St,JC082_JC023,destination
3,2021-01-05 22:53:03.5880,2021-01-05 22:56:30.7910,Brunswick-St,JC023,40.724,-74.051,member,Manila-and-1st_Brunswick-St,JC082_JC023,destination
4,2021-01-08 23:10:38.3990,2021-01-08 23:14:36.4990,Brunswick-St,JC023,40.724,-74.051,member,Manila-and-1st_Brunswick-St,JC082_JC023,destination
...,...,...,...,...,...,...,...,...,...,...
33616,2021-03-29 19:30:20,2021-03-29 19:38:10,Morris-Canal,JC072,40.712,-74.039,member,Harborside_Morris-Canal,JC104_JC072,destination
33617,2021-03-12 18:49:06,2021-03-12 18:54:35,Morris-Canal,JC072,40.712,-74.039,member,Harborside_Morris-Canal,JC104_JC072,destination
33618,2021-03-28 12:29:15,2021-03-28 12:34:40,Newark-Ave,JC032,40.722,-74.046,member,Harborside_Newark-Ave,JC104_JC032,destination
33619,2021-03-23 13:03:35,2021-03-23 13:10:25,Newark-Ave,JC032,40.722,-74.046,member,Harborside_Newark-Ave,JC104_JC032,destination
33620,2021-03-24 10:12:54,2021-03-24 10:21:17,Newark-Ave,JC032,40.722,-74.046,member,Harborside_Newark-Ave,JC104_JC032,destination

In [396]:
# Make column names consistent

origin_df.rename(columns={"start_station_name":"station_name", "start_station_id":"station_id", "start_lat":"latitude", "start_lng":"longitude"}, inplace=True)
origin_df

,started_at,ended_at,station_name,station_id,latitude,longitude,member_casual,path_id,path_id_2,origin_destination
0,2021-01-01 00:03:35.5100,2021-01-01 00:08:01.7770,Manila-and-1st,JC082,40.722,-74.043,member,Manila-and-1st_Brunswick-St,JC082_JC023,origin
1,2021-01-02 23:16:11.3820,2021-01-02 23:21:08.3150,Manila-and-1st,JC082,40.722,-74.043,member,Manila-and-1st_Brunswick-St,JC082_JC023,origin
2,2021-01-04 13:16:00.9080,2021-01-04 13:20:30.7690,Manila-and-1st,JC082,40.722,-74.043,member,Manila-and-1st_Brunswick-St,JC082_JC023,origin
3,2021-01-05 22:53:03.5880,2021-01-05 22:56:30.7910,Manila-and-1st,JC082,40.722,-74.043,member,Manila-and-1st_Brunswick-St,JC082_JC023,origin
4,2021-01-08 23:10:38.3990,2021-01-08 23:14:36.4990,Manila-and-1st,JC082,40.722,-74.043,member,Manila-and-1st_Brunswick-St,JC082_JC023,origin
...,...,...,...,...,...,...,...,...,...,...
33616,2021-03-29 19:30:20,2021-03-29 19:38:10,Harborside,JC104,40.719,-74.034,member,Harborside_Morris-Canal,JC104_JC072,origin
33617,2021-03-12 18:49:06,2021-03-12 18:54:35,Harborside,JC104,40.719,-74.034,member,Harborside_Morris-Canal,JC104_JC072,origin
33618,2021-03-28 12:29:15,2021-03-28 12:34:40,Harborside,JC104,40.719,-74.034,member,Harborside_Newark-Ave,JC104_JC032,origin
33619,2021-03-23 13:03:35,2021-03-23 13:10:25,Harborside,JC104,40.719,-74.034,member,Harborside_Newark-Ave,JC104_JC032,origin
33620,2021-03-24 10:12:54,2021-03-24 10:21:17,Harborside,JC104,40.719,-74.034,member,Harborside_Newark-Ave,JC104_JC032,origin

In [397]:
destination_df.rename(columns={"end_station_name":"station_name", "end_station_id":"station_id", "end_lat":"latitude", "end_lng":"longitude"}, inplace=True)
destination_df

,started_at,ended_at,station_name,station_id,latitude,longitude,member_casual,path_id,path_id_2,origin_destination
0,2021-01-01 00:03:35.5100,2021-01-01 00:08:01.7770,Brunswick-St,JC023,40.724,-74.051,member,Manila-and-1st_Brunswick-St,JC082_JC023,destination
1,2021-01-02 23:16:11.3820,2021-01-02 23:21:08.3150,Brunswick-St,JC023,40.724,-74.051,member,Manila-and-1st_Brunswick-St,JC082_JC023,destination
2,2021-01-04 13:16:00.9080,2021-01-04 13:20:30.7690,Brunswick-St,JC023,40.724,-74.051,member,Manila-and-1st_Brunswick-St,JC082_JC023,destination
3,2021-01-05 22:53:03.5880,2021-01-05 22:56:30.7910,Brunswick-St,JC023,40.724,-74.051,member,Manila-and-1st_Brunswick-St,JC082_JC023,destination
4,2021-01-08 23:10:38.3990,2021-01-08 23:14:36.4990,Brunswick-St,JC023,40.724,-74.051,member,Manila-and-1st_Brunswick-St,JC082_JC023,destination
...,...,...,...,...,...,...,...,...,...,...
33616,2021-03-29 19:30:20,2021-03-29 19:38:10,Morris-Canal,JC072,40.712,-74.039,member,Harborside_Morris-Canal,JC104_JC072,destination
33617,2021-03-12 18:49:06,2021-03-12 18:54:35,Morris-Canal,JC072,40.712,-74.039,member,Harborside_Morris-Canal,JC104_JC072,destination
33618,2021-03-28 12:29:15,2021-03-28 12:34:40,Newark-Ave,JC032,40.722,-74.046,member,Harborside_Newark-Ave,JC104_JC032,destination
33619,2021-03-23 13:03:35,2021-03-23 13:10:25,Newark-Ave,JC032,40.722,-74.046,member,Harborside_Newark-Ave,JC104_JC032,destination
33620,2021-03-24 10:12:54,2021-03-24 10:21:17,Newark-Ave,JC032,40.722,-74.046,member,Harborside_Newark-Ave,JC104_JC032,destination

In [398]:
# concatenate dataframes

frames = [origin_df, destination_df]

spider_map_df = pd.concat(frames, sort=False)
spider_map_df

,started_at,ended_at,station_name,station_id,latitude,longitude,member_casual,path_id,path_id_2,origin_destination
0,2021-01-01 00:03:35.5100,2021-01-01 00:08:01.7770,Manila-and-1st,JC082,40.722,-74.043,member,Manila-and-1st_Brunswick-St,JC082_JC023,origin
1,2021-01-02 23:16:11.3820,2021-01-02 23:21:08.3150,Manila-and-1st,JC082,40.722,-74.043,member,Manila-and-1st_Brunswick-St,JC082_JC023,origin
2,2021-01-04 13:16:00.9080,2021-01-04 13:20:30.7690,Manila-and-1st,JC082,40.722,-74.043,member,Manila-and-1st_Brunswick-St,JC082_JC023,origin
3,2021-01-05 22:53:03.5880,2021-01-05 22:56:30.7910,Manila-and-1st,JC082,40.722,-74.043,member,Manila-and-1st_Brunswick-St,JC082_JC023,origin
4,2021-01-08 23:10:38.3990,2021-01-08 23:14:36.4990,Manila-and-1st,JC082,40.722,-74.043,member,Manila-and-1st_Brunswick-St,JC082_JC023,origin
...,...,...,...,...,...,...,...,...,...,...
33616,2021-03-29 19:30:20,2021-03-29 19:38:10,Morris-Canal,JC072,40.712,-74.039,member,Harborside_Morris-Canal,JC104_JC072,destination
33617,2021-03-12 18:49:06,2021-03-12 18:54:35,Morris-Canal,JC072,40.712,-74.039,member,Harborside_Morris-Canal,JC104_JC072,destination
33618,2021-03-28 12:29:15,2021-03-28 12:34:40,Newark-Ave,JC032,40.722,-74.046,member,Harborside_Newark-Ave,JC104_JC032,destination
33619,2021-03-23 13:03:35,2021-03-23 13:10:25,Newark-Ave,JC032,40.722,-74.046,member,Harborside_Newark-Ave,JC104_JC032,destination
33620,2021-03-24 10:12:54,2021-03-24 10:21:17,Newark-Ave,JC032,40.722,-74.046,member,Harborside_Newark-Ave,JC104_JC032,destination

In [234]:
# Sort values by shared attributes to create (2) lat/lng records per trip - (1) origin, (1) destination

spider_map_df.sort_values(["started_at", "ended_at"], ascending=[True, True], inplace=True)
spider_map_df

,started_at,ended_at,station_name,station_id,latitude,longitude,member_casual,path_id,origin_destination
0,2021-01-01 00:03:35.5100,2021-01-01 00:08:01.7770,Manila & 1st,JC082,40.722,-74.043,member,JC082_JC023,origin
0,2021-01-01 00:03:35.5100,2021-01-01 00:08:01.7770,Brunswick St,JC023,40.724,-74.051,member,JC082_JC023,destination
8906,2021-01-01 00:23:32.9250,2021-01-01 00:49:16.0830,Grand St,JC102,40.715,-74.038,casual,JC102_JC035,origin
8906,2021-01-01 00:23:32.9250,2021-01-01 00:49:16.0830,Van Vorst Park,JC035,40.718,-74.048,casual,JC102_JC035,destination
8907,2021-01-01 00:23:50.7940,2021-01-01 00:48:12.5660,Grand St,JC102,40.715,-74.038,casual,JC102_JC035,origin
...,...,...,...,...,...,...,...,...,...
27273,2021-03-31 23:21:13,2021-03-31 23:26:11,Sip Ave,JC056,40.731,-74.064,member,JC093_JC056,destination
33072,2021-03-31 23:21:47,2021-03-31 23:24:11,Columbus Dr at Exchange Pl,JC106,40.717,-74.033,member,JC106_JC104,origin
33072,2021-03-31 23:21:47,2021-03-31 23:24:11,Harborside,JC104,40.719,-74.034,member,JC106_JC104,destination
20033,2021-03-31 23:41:03,2021-04-01 00:00:48,JC Medical Center,JC011,40.717,-74.050,casual,JC011_JC011,origin
20033,2021-03-31 23:41:03,2021-04-01 00:00:48,JC Medical Center,JC011,40.717,-74.050,casual,JC011_JC011,destination

In [235]:
spider_map_df.to_csv(r'/Users/amber/Desktop/GitHub/Tableau-DataClean/csvs/JAN-MAR-SPIDER-citibike-tripdata.csv', index=False)